<a href="https://colab.research.google.com/github/tuetamduong22949680/ASSESSMENT-2/blob/main/ISYS2001_Assessment2_Finance_Assistant_Draft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ISYS2001 Assessment 2 – Finance Assistant

# Step 1 – Understand the Problem

## Problem

Managing personal finances can become difficult when a person has different income sources, many expenses, household responsibilities and multiple saving goals.

A person's financial situation may also change over time.

Income may be regular or variable. Expenses may be fixed, flexible, seasonal, temporary or one-off. Some costs may be shared with other people, while some income may only be available for a specific person or purpose.

Because of this, a simple fixed budget may not accurately represent the user's real financial situation.

Users may know roughly how much they earn and spend, but they may not know:

- how much of their income is actually available to use
- how much of each shared expense they are personally responsible for
- how much money is left after essential expenses
- how much money should be kept as a safety or emergency buffer
- how much they can realistically save
- whether they can reach multiple saving goals by their deadlines
- which goals should be prioritised when money is limited
- which expenses could realistically be reduced
- how changes in income or spending affect their saving goals
- whether they have forgotten important expenses when creating their budget

## Proposed Solution

The project will create a **Smart Savings and Spending Planner**.

The application will build a personalised financial plan using information about the user's:

- personal and household profile
- income sources
- financial responsibilities
- expenses
- existing savings
- saving goals

The profile will help the application understand the user's situation and decide which possible expenses and follow-up questions are relevant.

## Profile

The user can build their profile by selecting different options that apply to their situation.

The profile can include:

- study or employment situation
- people living with the user
- people the user supports outside the household
- dependants
- shared responsibilities
- pets
- other relevant household situations

The profile will be flexible so that multiple situations can be combined instead of forcing every user into one fixed family type.

Uncommon situations can be entered using an **Other** option and Gemini can help interpret the description.

## Income

The application will support multiple income sources.

Income information may include:

- amount
- payment frequency
- person receiving the income
- whether the income is regular, variable, seasonal, temporary or one-off
- how much of the income is actually available for the budget
- whether the income is restricted to a specific purpose

For variable income, the application can track income across multiple payment periods instead of assuming that one period represents the user's normal income.

The user will enter take-home or usable income where possible so that the budget is based on money that can actually be spent.

## Expenses

The user will first describe their expenses naturally instead of completing a very long checklist.

Gemini will extract as much information as possible from the user's description, including:

- expense category
- amount
- frequency
- who the expense relates to
- who pays the expense
- whether the expense is shared
- whether the expense is regular, variable, seasonal, temporary or one-off

The extracted information will be shown back to the user for confirmation before calculations are performed.

The application will then compare the extracted expenses with a list of possible expenses based on the user's profile.

Expenses already identified will be filled automatically.

Only possible missing expenses will be shown to the user.

For example, if a user enters rent but does not mention household bills, the application may ask whether electricity, water, gas or internet are included in the rent.

Missing information will not automatically be treated as zero.

It can instead be recorded as:

- unknown
- not applicable
- paid by someone else
- not yet entered

Expenses will also be classified into useful budgeting groups such as:

- fixed expenses
- essential flexible expenses
- optional flexible expenses

The user will be able to correct the classification if necessary.

Refunds, reimbursements and transfers between the user's own accounts should not automatically be treated as normal income or normal spending.

## Saving Goals

The application will support multiple saving goals.

Each goal may contain:

- goal name
- target amount
- currency
- amount already saved for that goal
- deadline
- priority
- whether the deadline can be changed
- the user's share of the goal if another person is contributing

The user may also have existing savings that have not yet been assigned to a specific goal.

These will be kept separate so that the same savings are not accidentally counted towards multiple goals.

Goals may also be ongoing or have no fixed deadline, such as building an emergency fund.

## Financial Calculations

Python will perform the main financial calculations.

The calculations will include:

- normalising different income and expense frequencies
- calculating usable income
- calculating the user's actual share of expenses
- calculating total spending
- calculating available money after expenses
- allowing for an emergency or safety buffer where appropriate
- calculating how much must be saved for each goal
- checking whether goals can be reached by their deadlines
- comparing multiple goals using their priorities and deadlines

Gemini will support the conversation and explain results, but the main financial numbers will come from Python calculations using the user's data.

## Building the Plan

If the user's current income and spending are enough to reach the goals, the application will create a suggested saving plan.

If the goals are not achievable, the application will look for realistic alternatives.

Possible suggestions may include:

- reducing optional flexible expenses
- reducing some essential flexible expenses where reasonable
- using unallocated savings
- changing a goal amount
- extending a flexible deadline
- changing the priority of a lower-priority goal

The application should avoid suggesting reductions to fixed or essential expenses before more flexible options are considered.

The user can accept or reject each suggested change.

The application will recalculate the plan after each accepted change.

If the user rejects the available changes and the goals still cannot be reached, the application will explain that it cannot find a realistic way to achieve all of the goals under the current conditions.

It may then allow the user to change a deadline, goal amount or priority, or continue with the current plan while showing the expected shortfall.

## Ongoing Tracking

After a plan is created, the user can continue tracking actual income and spending.

Income can be recorded each payment cycle and expenses can be entered manually or loaded from transaction data where appropriate.

The application can compare:

- expected income against actual income
- planned spending against actual spending
- planned saving against actual saving
- expected goal progress against actual progress

If the user's financial situation changes, the application can recalculate the plan.

For example, if income decreases or spending increases, the application can show how this may affect the expected completion date of a saving goal.

## Gemini's Role

Gemini will be used as the conversational part of the assistant.

Gemini can help:

- understand natural-language user input
- extract financial information
- identify information that may be missing
- ask relevant follow-up questions
- explain calculation results in simple language
- discuss possible budgeting changes

Gemini should not invent missing financial information.

If important information is unclear, it should ask the user for clarification.

The user should be able to review and correct information interpreted by Gemini before it is used for important calculations.

If the user asks something unclear or unrelated to the purpose of the application, the assistant should respond sensibly and guide the conversation back to personal budgeting and saving.

## Target Users

The application can support different users, including:

- students
- workers
- self-employed users
- families
- retired users
- users with shared households
- users with dependants or complex financial responsibilities

The application will adapt its questions and possible expense suggestions based on the user's profile instead of giving every user the same long form.

## Scope

The application is designed to provide personal budgeting and saving guidance based on information entered by the user.

It is not intended to provide professional investment, tax or legal advice.

The application will help users understand and organise their own financial data rather than make financial decisions for them.

## Main Goal

The main goal of the application is to help users create a realistic and personalised saving and spending plan based on their actual financial situation.

The application will combine Gemini for conversation and understanding natural-language input with Python for financial calculations, planning and ongoing tracking.

# Step 2 – Identify Inputs and Outputs

## Purpose of This Step

This step identifies the information the application needs from the user and the results the application should produce.

The main rule is that the application should only calculate with information that has been confirmed or clearly classified.

The application should not guess missing financial amounts.

---

# Inputs

## 1. Base Budget Settings

Before calculations are performed, the application needs a common basis for comparing financial information.

The user will select:

- base currency
- preferred budgeting period

Possible budgeting periods include:

- weekly
- fortnightly
- monthly

All income, expenses and saving requirements will later be converted into the same budgeting period before calculations are performed.

If the user has income, expenses or goals in another currency, the original currency will still be stored, but the value will be converted into the selected base currency for calculations.

---

## 2. User Profile

The user can select one or more situations that describe them.

Possible options include:

- Student
- Working
- Self-employed
- Retired
- Not currently working
- Other

Multiple options can apply at the same time.

For example:

- Student + Working
- Retired + Part-time Working

The profile is used to decide which follow-up questions and possible expenses may be relevant.

---

## 3. People in the User's Financial Situation

The user can add people who are financially relevant to their situation.

For each person, the application may record:

- relationship to the user
- whether they live with the user
- age group where relevant
- whether the user financially supports them
- whether the user provides care
- whether responsibility is shared with another person
- whether the person has their own income where relevant

Common relationship options may include:

- Partner
- Child
- Parent
- Sibling
- Grandparent
- Housemate
- Other

Less common situations can be entered using **Other**.

Gemini may help interpret unusual descriptions, but the user must confirm the result.

---

## 4. Pets

The user may add pets where relevant.

The application may record:

- pet type
- quantity
- whether the user is financially responsible for the pet
- whether the cost is shared with another person

Actual pet costs will be entered later as expenses.

---

# Income Inputs

## 5. Income Sources

The user can add one or more income sources.

Each source should be recorded separately.

For each income source, the application may need:

- income name or type
- person receiving the income
- amount
- currency
- payment frequency
- income pattern
- whether the amount entered is typical
- whether the income is recurring
- how much is available to the current budget
- whether the income is restricted to a specific purpose

Possible income types include:

- Salary
- Casual work
- Self-employment
- Pension
- Government payment
- Child support received
- Investment income
- Other

Possible income patterns include:

- Regular
- Variable
- Seasonal
- Temporary
- One-off
- Irregular

---

## 6. Income Frequency

Possible frequencies include:

- Weekly
- Fortnightly
- Monthly
- Yearly
- Irregular

For variable income, the application may collect several recent periods.

For example:

- Week 1: $450
- Week 2: $300
- Week 3: $0
- Week 4: $500

This allows the program to calculate a more realistic value instead of assuming that one payment period represents normal income.

A period with **$0 income** must be different from a period where the user has **not entered any data**.

Possible tracking states should therefore include:

- Income entered
- No income this period
- Missing record

---

## 7. Usable Income

Not all money received should automatically be treated as money available for all purposes.

For each income source, the application should identify whether the money is:

- fully available
- partly available
- available as a fixed contribution
- restricted to a specific purpose
- not available to this budget

Example:

A partner may earn $1,000 per week but only contribute $300 to shared household costs.

Only the relevant contribution should be used in the shared budget.

---

## 8. Restricted Income

Some income may only be used for a specific purpose.

Examples include:

- scholarship money for tuition
- child support intended for child-related expenses
- financial assistance for medical costs

Restricted income should not automatically be included in the general money available for saving goals.

It should first be matched to its intended purpose.

---

## 9. Self-Employment or Business Income

For self-employed users, the application should avoid treating business revenue as personal income.

The application may ask whether the entered amount is:

- take-home income
- net profit after business expenses
- gross revenue before business expenses

Where possible, the financial plan should use the amount that is actually available to the user after relevant business costs.

---

## 10. Future Income Changes

The user may indicate if an income source is expected to change.

Possible options include:

- No expected change
- Starting soon
- Ending soon
- Expected to increase
- Expected to decrease
- Not sure

This prevents the application from assuming that current income will always continue unchanged.

---

# Expense Inputs

## 11. Natural-Language Expense Description

The user will first be allowed to describe their expenses naturally.

Example:

> "I pay $450 rent each week, around $120 for groceries, $70 petrol, and $50 phone each month. My partner pays half the rent."

Gemini will try to extract as much information as possible.

Possible information to extract includes:

- expense category
- amount
- currency
- frequency
- who the expense relates to
- who pays it
- user's share
- whether it is shared
- expense pattern
- start or end date where relevant

Gemini should only fill information that can reasonably be identified from the user's description.

It should not invent missing amounts, frequencies or sharing rules.

---

## 12. Expense Confirmation

After Gemini extracts the expense information, the application will show the result back to the user.

The user can:

- Confirm
- Edit
- Add
- Remove

Only confirmed information should be used for important financial calculations.

---

## 13. Missing Expense Check

The application will compare the confirmed expenses with a list of possible expenses that may apply to the user's profile.

Expenses already identified will not be asked again.

Only possible missing expenses will be shown.

For example:

If the user enters rent but does not mention utilities, the application may ask:

> Are electricity, water, gas or internet included in your rent?

The user may answer:

- All included
- Some included
- Not included
- Not sure

If some are not included, the relevant expenses can then be added.

---

## 14. Expense Status

A missing expense should not automatically be treated as zero.

Possible statuses include:

- Confirmed
- Unknown
- Not applicable
- Paid by someone else
- Missing information
- Estimated

This prevents missing information from incorrectly changing the budget result.

---

## 15. Expense Categories

Expenses may include categories such as:

- Housing
- Utilities
- Food
- Transport
- Study
- Work
- Children
- Dependants
- Health
- Pets
- Debt repayments
- Subscriptions
- Lifestyle
- Hobbies
- Other

The exact categories shown to the user may depend on their profile.

---

## 16. Expense Flexibility

Each expense should be classified where possible as:

### Fixed

Expenses that are difficult to change in the short term.

Examples:

- rent
- mortgage
- required loan repayments

### Essential Flexible

Necessary expenses where the amount may sometimes be adjusted.

Examples:

- groceries
- petrol
- utilities

### Optional Flexible

Expenses that are easier to reduce if necessary.

Examples:

- entertainment
- eating out
- shopping
- hobbies

The user should be able to correct the classification.

---

## 17. Expense Pattern

Expenses may have different patterns.

Possible patterns include:

- Regular
- Variable
- Seasonal
- Temporary
- One-off
- Irregular

Where relevant, the application may also record:

- start date
- end date
- next payment date
- due date

This is important for expenses such as:

- annual insurance
- school fees
- temporary childcare
- seasonal electricity bills

---

## 18. Shared Expenses

For a shared expense, the application should record:

- total expense
- user's actual share
- other person's contribution where relevant

Only the user's actual responsibility should be counted as the user's expense.

Example:

Rent = $600 per week

User pays = $300

Partner pays = $300

The user's budget expense should be $300, not $600.

---

## 19. Direct Payments by Other People

If another person directly pays part of an expense, the application should not also count that payment as income to the user.

Example:

Partner directly pays $300 of the rent.

The application should reduce the user's rent responsibility by $300.

It should not:

1. reduce the user's rent, and
2. add another $300 to the user's income.

This would count the same money twice.

---

## 20. Complex Expense Arrangements

Some expenses may have very complicated arrangements.

Examples include:

- insurance deductibles
- changing sharing percentages
- reimbursements
- usage-based cost sharing
- temporary contributions from relatives

If the application cannot safely calculate the full arrangement, it should ask:

> What amount actually comes out of your budget?

The confirmed out-of-pocket amount can then be used for the financial plan.

This is safer than allowing the program to guess a complicated allocation.

---

## 21. Refunds and Reimbursements

Refunds and reimbursements should be recorded separately from normal income.

Examples:

- insurance refund
- returned purchase
- employer reimbursement

A reimbursement should normally reduce the related expense rather than be treated as recurring income.

---

## 22. Internal Transfers

Transfers between the user's own accounts should not be treated as income or expenses.

Examples:

- everyday account to savings account
- savings account to transaction account

These transactions only move money between accounts owned by the user.

---

## 23. Credit Card Transactions

Credit card spending should not be counted twice.

Example:

The user buys $100 of groceries using a credit card.

The $100 grocery purchase is the expense.

When the user later pays $100 from their bank account to the credit card, this should not create another $100 expense.

Interest and credit card fees may still be treated as separate expenses.

---

## 24. Debt Repayments

Required debt repayments should be treated as expenses.

Examples:

- minimum credit card repayment
- personal loan repayment
- car loan repayment

Extra payments made to reduce debt faster may instead be treated as a financial goal.

This prevents the same debt payment from being counted as both a required expense and a saving goal.

---

# Savings Inputs

## 25. Existing Savings

Existing savings should be separated into:

### Allocated Savings

Money already assigned to a specific goal.

Example:

$700 already saved for a new computer.

### Unallocated Savings

Savings that have not yet been assigned to a specific goal.

Example:

$2,000 general savings.

The same savings amount must not be assigned to more than one place at the same time.

---

## 26. Savings Transfers

Moving money from a spending account into a savings account should not be treated as a normal expense.

It represents an allocation of existing money rather than consumption.

---

# Saving Goal Inputs

## 27. Saving Goals

The user can create one or more goals.

For each goal, the application may record:

- goal name
- target amount
- currency
- deadline
- priority
- deadline flexibility
- user's share of the goal
- contribution from another person
- savings already allocated to the goal

Possible priority levels include:

- Must have
- Important
- Nice to have

Possible deadline options include:

- Fixed
- Flexible
- No fixed deadline

---

## 28. Shared Goals

If another person contributes to a goal, that contribution should reduce the user's required share.

It should not automatically be added to the user's general income.

Example:

Trip cost = $4,000

Partner contribution = $2,000

User responsibility = $2,000

The user's saving target should therefore be $2,000.

---

## 29. Ongoing Goals

Some goals may not have a fixed deadline.

Examples:

- emergency fund
- general long-term savings

These goals can be treated as ongoing goals instead of forcing an artificial deadline.

---

# Safety Buffer Input

## 30. Budget Safety Buffer

The application may allow the user to keep some money unallocated as a safety buffer.

Possible options include:

- No safety buffer
- Set my own amount
- Let the application suggest an amount

If the application suggests a buffer, the user must confirm it before it becomes part of the plan.

A short-term budget safety buffer is different from an emergency fund saving goal.

---

# Ongoing Tracking Inputs

## 31. Actual Income Tracking

During future budgeting periods, the user can record actual income.

This allows the program to compare:

- expected income
- actual income

Variable income can be recalculated as more periods are recorded.

---

## 32. Actual Expense Tracking

The user may record actual expenses through:

- manual entry
- natural-language entry
- CSV transaction data

The application should classify transactions before using them in calculations.

Possible transaction types include:

- real expense
- income
- refund
- reimbursement
- internal transfer
- savings transfer
- debt payment
- unknown

---

## 33. Duplicate Transactions

If transaction data is uploaded more than once, the application should avoid counting the same transaction multiple times where possible.

Possible duplicate information may include:

- same date
- same amount
- same description

Possible duplicates should be reviewed before being added again.

---

# Important Processing Rules

Before producing financial outputs, the application should follow these rules.

## Rule 1 – Do Not Double Count Money

The same amount should only affect the budget once.

Examples include:

- shared expenses
- partner contributions
- credit card payments
- savings transfers
- refunds
- goal contributions

---

## Rule 2 – Missing Does Not Mean Zero

Unknown information must remain unknown until the user confirms it.

---

## Rule 3 – Only Count the User's Real Responsibility

For shared expenses, only the user's share should reduce their available money.

---

## Rule 4 – Restricted Money Must Stay Restricted

Income restricted to a purpose should not be used for unrelated saving goals.

---

## Rule 5 – Existing Savings Are Not Income

Savings represent money already owned by the user.

They should not be counted again as new income.

---

## Rule 6 – Internal Transfers Are Not Spending

Moving money between the user's own accounts should not change total wealth.

---

## Rule 7 – Use One Base Currency

All amounts must be converted to the user's base currency before being combined.

---

## Rule 8 – Use One Budgeting Period

Income and expenses must be normalised into the same budgeting period before comparison.

---

## Rule 9 – Required Costs Come Before Saving Goals

Required financial obligations should be covered before money is allocated to optional saving goals.

---

## Rule 10 – Gemini Does Not Decide Financial Numbers

Gemini can:

- extract
- classify
- explain
- ask questions

Python will perform the final financial calculations using confirmed data.

---

# Outputs

## 1. Profile Summary

The application will show a summary of the user's financial situation.

This may include:

- user situation
- household members
- dependants
- people supported outside the household
- pets
- financial responsibilities

The user can review and correct the summary.

---

## 2. Income Summary

The application will show:

- income sources
- normalised income
- general usable income
- restricted income
- variable income information
- contributions from other household members
- expected future income changes

---

## 3. Expense Summary

The application will show:

- confirmed expenses
- user's actual share
- fixed expenses
- essential flexible expenses
- optional flexible expenses
- variable or seasonal expenses
- missing or uncertain expenses
- expenses paid by another person

---

## 4. Savings Summary

The application will show:

- allocated savings
- unallocated savings
- savings assigned to each goal

The same savings amount should never appear in multiple categories at the same time.

---

## 5. Normalised Budget Summary

Before goal calculations, the application will convert relevant financial values into:

- the selected base currency
- the selected budgeting period

Example:

**Weekly Budget**

- General usable income: $1,000
- Required expenses: $700
- Money remaining: $300

---

## 6. Money Available Before Goals

The basic calculation will be:

**Money remaining before goals = General usable income - Required expenses**

Restricted income will be handled separately.

---

## 7. Money Available for Saving Goals

If the user chooses a safety buffer:

**Money available for goals = Money remaining before goals - Accepted safety buffer**

If no safety buffer is used:

**Money available for goals = Money remaining before goals**

---

## 8. Goal Analysis

For each goal, the application will show:

- target amount
- savings already allocated
- remaining amount required
- time remaining
- required saving per budgeting period
- priority
- deadline flexibility
- whether the goal is currently achievable

---

## 9. Overall Feasibility Result

The application will determine whether the user's available money is enough to support the saving goals.

Possible results include:

- All goals achievable
- Some goals achievable
- Goals require adjustment
- No realistic plan found under the current conditions

---

## 10. Suggested Saving Plan

If the goals are achievable, the application will show a suggested allocation.

Example:

- PC goal: $45 per week
- Flight goal: $30 per week
- Safety buffer: $10 per week
- Remaining flexible money: $15 per week

---

## 11. Adjustment Suggestions

If the plan is not achievable, the application may suggest changes based on:

- expense flexibility
- goal priority
- deadline flexibility
- available unallocated savings

Possible suggestions include:

- reduce optional flexible spending
- reduce an adjustable essential expense
- use some unallocated savings
- extend a flexible deadline
- reduce a lower-priority goal
- change goal priority

The application will not automatically change the user's plan.

The user must accept or reject each change.

---

## 12. Updated Plan

After the user accepts a change, Python will recalculate the plan.

The new result will show:

- updated expenses
- updated available money
- updated goal contributions
- updated expected completion dates

---

## 13. No Feasible Plan Result

If the goals remain unachievable after the available options have been considered or rejected, the application will state that it cannot find a realistic plan under the current conditions.

The application may show:

- total shortfall
- which goals are affected
- which deadlines cannot currently be met

The user can then choose to change:

- target amount
- deadline
- priority
- income information
- expense information

---

## 14. Tracking Review

After real income and spending are recorded, the application can show:

- expected income versus actual income
- planned expenses versus actual expenses
- spending over or under budget
- planned savings versus actual savings
- current goal balances
- updated expected goal completion dates

---

## 15. Replanning Output

If actual results are different from the original plan, the application can recalculate the financial plan.

Example:

> Your income was $80 lower than expected and your food spending was $25 above the plan. If this pattern continues, your PC goal may take longer to complete.

The user can then:

- keep the current plan
- adjust the budget
- update income information
- change a goal
- create a new plan

---

# Final Input-to-Output Flow

The overall data flow will be:

**Profile**

↓

**Income Sources**

↓

**Natural-Language Expense Description**

↓

**Gemini Extracts Information**

↓

**User Confirms Extracted Information**

↓

**Application Checks for Possible Missing Expenses**

↓

**User Completes Missing Information**

↓

**Existing Savings**

↓

**Saving Goals**

↓

**Convert to Base Currency and Budgeting Period**

↓

**Python Calculates the User's Real Financial Position**

↓

**Goal Feasibility Analysis**

↓

**Suggested Plan or Adjustment Options**

↓

**User Accepts or Rejects Changes**

↓

**Final Saving and Spending Plan**

↓

**Actual Income and Expense Tracking**

↓

**Review and Re-plan When Needed**

# Step 3 – Work Through an Example by Hand

## Purpose

Before writing Python code, I will work through one complete example manually.

This example is designed to check that the financial logic works before it is converted into code.

The example includes:

- variable income
- another household member contributing money
- restricted income
- weekly and monthly expenses
- missing expense checking
- shared household finances
- different expense types
- existing savings
- multiple saving goals
- different priorities
- a safety buffer
- an initially unachievable plan
- an adjustment suggested by the application
- recalculation after the user accepts the suggestion

The main objective is to make sure that money is not double counted and that only money that is actually available is used for saving goals.

---

# Example User

## Profile

The example user:

- is working
- lives with a partner
- has one child
- shares household expenses with their partner
- receives child support for the child

The user's selected settings are:

- Base currency: AUD
- Budgeting period: Weekly
- Planning date: 12 October 2026

All calculations will therefore be converted into Australian dollars per week.

---

# 1. Income Information

## User's Employment Income

The user's income changes slightly each week.

Recent take-home income:

| Week | Income |
|---|---:|
| Week 1 | $950 |
| Week 2 | $1,020 |
| Week 3 | $980 |
| Week 4 | $1,050 |

The user confirms that these four weeks are reasonably normal.

### Average Weekly Employment Income

Average income:

($950 + $1,020 + $980 + $1,050) / 4

= $4,000 / 4

= **$1,000 per week**

Therefore:

**User employment income = $1,000 per week**

No missing week is treated as $0.

In this example, all four weeks contain confirmed income records.

---

## Partner Contribution

The partner transfers:

**$350 per week**

into the shared household budget.

Because the money is actually transferred into the household budget, it can be counted as a household contribution.

Therefore:

**Partner contribution = $350 per week**

This contribution will only be counted once.

The application must not also reduce the user's expenses using the same $350 unless the partner separately pays an expense directly.

---

## Child Support

The user receives:

**$120 per week**

in child support.

The user confirms that this money is intended for child-related costs.

Therefore it is classified as:

**Restricted income = $120 per week**

It should not be treated as general money that can be used for:

- the PC goal
- travel
- entertainment
- unrelated saving goals

---

## Income Summary

### General Usable Money

User employment income:

$1,000

Partner household contribution:

+ $350

General usable money:

**$1,350 per week**

### Restricted Money

Child support:

**$120 per week**

### Total Money Entering the Household Budget

$1,350 + $120

= **$1,470 per week**

However, only **$1,350** is general-purpose money.

The other **$120** remains restricted to child-related costs.

---

# 2. Initial Expense Description

The user enters:

> "Rent is $520 a week. Groceries are around $170 a week. I spend about $45 on the bus each week. My phone is $60 a month, childcare is $220 a week, Netflix is $30 a month and I normally spend around $80 a week going out."

Gemini extracts the following information:

| Expense | Amount | Frequency |
|---|---:|---|
| Rent | $520 | Weekly |
| Groceries | $170 | Weekly |
| Public transport | $45 | Weekly |
| Phone | $60 | Monthly |
| Childcare | $220 | Weekly |
| Streaming | $30 | Monthly |
| Going out | $80 | Weekly |

The user confirms that the extracted amounts are correct.

Gemini does not invent any expenses that were not mentioned.

---

# 3. Missing Expense Check

The user's profile shows that they rent a home.

The expense list contains rent but does not contain household utilities.

The application therefore asks:

> Are household bills included in your rent?

The user answers:

- Water: Included
- Internet: Included
- Gas: Not used
- Electricity: Not included

The application then asks for electricity.

The user enters:

**Electricity = $180 per month**

The expense list is updated.

This shows why missing information should not automatically be treated as $0.

Electricity was initially missing, not zero.

---

# 4. Classify Expenses

The confirmed expenses are classified as follows.

| Expense | Classification |
|---|---|
| Rent | Fixed |
| Groceries | Essential Flexible |
| Public transport | Essential Flexible |
| Phone | Fixed / Essential |
| Electricity | Essential Flexible |
| Childcare | Fixed / Essential |
| Streaming | Optional Flexible |
| Going out | Optional Flexible |

The classification is used later when the application looks for possible spending reductions.

It does not change whether the current expense is included in the baseline budget.

All confirmed current expenses are included first.

---

# 5. Normalise Expense Frequencies

The budgeting period is weekly.

Weekly expenses can be used directly.

Monthly expenses must be converted into a weekly equivalent.

The conversion used is:

**Weekly equivalent = Monthly amount × 12 / 52**

This is more accurate than simply dividing a monthly amount by 4.

---

## Phone

Monthly phone cost:

$60

Weekly equivalent:

$60 × 12 / 52

= $720 / 52

= **$13.846...**

Displayed amount:

**$13.85 per week**

---

## Electricity

Monthly electricity cost:

$180

Weekly equivalent:

$180 × 12 / 52

= $2,160 / 52

= **$41.538...**

Displayed amount:

**$41.54 per week**

---

## Streaming

Monthly streaming cost:

$30

Weekly equivalent:

$30 × 12 / 52

= $360 / 52

= **$6.923...**

Displayed amount:

**$6.92 per week**

---

# 6. Rounding Rule

The application should keep the full calculated values internally where possible.

The amounts should normally be rounded to two decimal places only when displayed to the user.

This reduces small calculation errors caused by repeatedly rounding intermediate values.

---

# 7. Handling the Restricted Child Support

Childcare costs:

**$220 per week**

Restricted child support available:

**$120 per week**

The restricted child support can be applied to childcare.

Remaining childcare cost that must come from the general household budget:

$220 - $120

= **$100 per week**

Therefore:

- $120 childcare is funded by restricted child support
- $100 childcare is funded by general usable money

The $120 child support must not also be added to the money available for saving goals.

---

# 8. Weekly Expense Calculation

The amount that must be funded from general-purpose money is:

| Expense | Weekly General-Budget Cost |
|---|---:|
| Rent | $520.00 |
| Groceries | $170.00 |
| Public transport | $45.00 |
| Phone | $13.85 |
| Electricity | $41.54 |
| Childcare after restricted support | $100.00 |
| Streaming | $6.92 |
| Going out | $80.00 |

Total:

$520  
+ $170  
+ $45  
+ $13.846...  
+ $41.538...  
+ $100  
+ $6.923...  
+ $80

= **$977.307...**

Displayed:

**General-budget expenses = $977.31 per week**

---

# 9. Cross-Check the Calculation

A second calculation can be used to confirm that restricted money has not been double counted.

## Full Household Expenses

Using the full childcare expense:

$520  
+ $170  
+ $45  
+ $13.846...  
+ $41.538...  
+ $220  
+ $6.923...  
+ $80

= **$1,097.307...**

Total money entering the household budget:

**$1,470**

Remaining:

$1,470 - $1,097.307...

= **$372.692...**

Now check using general-purpose money only:

General usable money:

$1,350

General-budget expenses after the child support offset:

$977.307...

$1,350 - $977.307...

= **$372.692...**

Both methods produce the same result.

This confirms that the $120 child support has only been counted once.

---

# 10. Money Remaining Before Saving Goals

General usable money:

$1,350

General-budget expenses:

- $977.307...

Money remaining:

$1,350 - $977.307...

= **$372.692...**

Displayed:

**$372.69 per week remaining**

---

# 11. Safety Buffer

The application suggests keeping some money unallocated for unexpected small costs.

The user chooses:

**$50 per week safety buffer**

The user confirms this amount.

The safety buffer is not the same as an emergency fund saving goal.

It is simply money that is not immediately committed to normal spending or goals.

Money available for saving goals:

$372.692... - $50

= **$322.692...**

Displayed:

**$322.69 per week available for saving goals**

---

# 12. Existing Savings

The user currently has:

- $300 already allocated to the Flight goal
- $200 already allocated to the PC goal
- $0 allocated to the Bag goal
- $0 unallocated savings

Total existing allocated savings:

$300 + $200

= **$500**

This $500 is existing money.

It is not counted as new weekly income.

The same $500 must not be counted again somewhere else.

---

# 13. Saving Goals

The user has three goals.

## Goal 1 – Flight

Target:

**$1,500**

Already allocated:

**$300**

Remaining:

$1,500 - $300

= **$1,200**

Deadline:

21 December 2026

The worked example assumes:

**10 weekly saving periods remain**

Priority:

**Must have**

Deadline:

**Fixed**

Required weekly saving:

$1,200 / 10

= **$120 per week**

---

## Goal 2 – PC

Target:

**$3,500**

Already allocated:

**$200**

Remaining:

$3,500 - $200

= **$3,300**

Deadline:

1 February 2027

The worked example assumes:

**16 weekly saving periods remain**

Priority:

**Important**

Deadline:

**Flexible**

Required weekly saving:

$3,300 / 16

= **$206.25 per week**

---

## Goal 3 – Bag

Target:

**$400**

Already allocated:

**$0**

Remaining:

**$400**

Deadline:

1 February 2027

Weekly saving periods remaining:

**16**

Priority:

**Nice to have**

Deadline:

**Flexible**

Required weekly saving:

$400 / 16

= **$25 per week**

---

# 14. Total Saving Requirement

Flight:

$120

PC:

+ $206.25

Bag:

+ $25

Total:

**$351.25 per week**

---

# 15. Feasibility Check

Money available for goals:

**$322.692... per week**

Money required for goals:

**$351.25 per week**

Shortfall:

$351.25 - $322.692...

= **$28.557...**

Displayed:

**Shortfall = $28.56 per week**

Therefore:

**The current plan is not achievable without a change.**

The application should not call the goals impossible.

It should explain that they are not achievable under the current confirmed income, expenses, buffer and deadlines.

---

# 16. Find Possible Adjustments

The application should not immediately suggest reducing fixed or essential expenses.

It first examines optional flexible expenses.

Current optional flexible expenses include:

- Going out: $80 per week
- Streaming: approximately $6.92 per week

The current shortfall is:

**$28.56 per week**

The application could suggest:

> Reducing going out by $30 per week would cover the current shortfall. Would you like to change your going-out budget from $80 to $50 per week?

Options:

- Accept
- Keep current amount
- Enter another amount

The application does not automatically change the expense.

---

# 17. User Accepts the Suggestion

The user selects:

**Accept**

Going out changes from:

$80

to:

**$50 per week**

Money saved:

**$30 per week**

---

# 18. Recalculate Expenses

Previous general-budget expenses:

$977.307...

Reduction:

- $30

New general-budget expenses:

$977.307... - $30

= **$947.307...**

Displayed:

**$947.31 per week**

---

# 19. Recalculate Available Money

General usable money:

$1,350

New expenses:

- $947.307...

Money remaining:

$1,350 - $947.307...

= **$402.692...**

Safety buffer:

- $50

Money available for saving goals:

$402.692... - $50

= **$352.692...**

Displayed:

**$352.69 per week**

---

# 20. Recheck Saving Goals

Saving required:

**$351.25 per week**

Money available:

**$352.692... per week**

Difference:

$352.692... - $351.25

= **$1.442...**

Displayed:

**$1.44 per week remaining**

The plan is now mathematically achievable.

However, it is very tight.

The application should explain this instead of simply displaying "Success".

For example:

> Your current plan can reach all three goals, but it is tight. After your planned expenses, $50 safety buffer and goal contributions, only about $1.44 per week remains unallocated.

---

# 21. Final Weekly Plan

## General Income

User income:

**$1,000.00**

Partner household contribution:

**$350.00**

Total general usable money:

**$1,350.00**

Restricted child support:

**$120.00**

---

## Current General-Budget Expenses

| Expense | Weekly Amount |
|---|---:|
| Rent | $520.00 |
| Groceries | $170.00 |
| Public transport | $45.00 |
| Phone provision | $13.85 |
| Electricity provision | $41.54 |
| Childcare paid from general budget | $100.00 |
| Streaming | $6.92 |
| Going out | $50.00 |

General-budget expenses:

**$947.31 per week**

Childcare funded separately by restricted child support:

**$120 per week**

---

## Saving and Buffer Allocation

Safety buffer:

**$50.00 per week**

Flight:

**$120.00 per week**

PC:

**$206.25 per week**

Bag:

**$25.00 per week**

Remaining unallocated amount:

**approximately $1.44 per week**

---

# 22. Final Balance Check

General usable money:

**$1,350**

Allocated from general money:

General expenses:

$947.307...

Safety buffer:

+ $50

Saving goals:

+ $351.25

Remaining:

+ $1.442...

Total:

**$1,350**

The calculation balances.

No money has been created or counted twice.

---

# 23. What If the User Rejects the Suggestion?

If the user rejects reducing going out, the application should not force the change.

It should look for another realistic option.

Because the goals have priorities, the application may examine the lower-priority and flexible goals next.

For example:

- Bag = Nice to have
- PC = Important
- Flight = Must have

Possible alternatives may include:

- delay the Bag goal
- extend the flexible PC deadline
- reduce the Bag target
- use unallocated savings if any exist
- choose a smaller spending reduction

The user can accept or reject each option.

If the user rejects all realistic changes, the application should return a result such as:

> Based on your current income, confirmed expenses, saving goals and the changes you are willing to make, I cannot find a realistic way to achieve all three goals by their current deadlines.

The application can then allow the user to change:

- a deadline
- a target amount
- a priority
- income information
- expense information

It should not pretend that an achievable plan exists when the numbers do not support it.

---

# 24. Important Rule for Monthly and Annual Bills

A monthly or annual bill needs special treatment when the user uses a weekly budget.

For example:

Phone bill:

**$60 per month**

Weekly budget provision:

**approximately $13.85 per week**

The $13.85 represents money that should be set aside over time for the future phone bill.

When the actual $60 payment happens, the application must not treat:

- the weekly provisions, and
- the $60 payment

as two separate expenses.

That would double count the same cost.

The same rule applies to:

- annual insurance
- registration
- school fees
- quarterly utilities
- other less-frequent bills

The application should distinguish between:

1. money being reserved for a future expense, and
2. the actual payment of that expense.

If a large bill is due soon and the user has not already saved enough for it, simply dividing the annual or monthly cost into future weekly amounts may not be enough.

The application may need to calculate a temporary catch-up amount based on:

- amount still required
- money already reserved
- time until the due date

This prevents a bill from appearing affordable on average when the user does not actually have enough money available when it becomes due.

---

# 25. Important Rule for Restricted Money

Restricted money must remain separate until it is used for its intended purpose.

In this example:

Child support = $120 per week

Childcare = $220 per week

The $120 can reduce the amount of childcare that must be paid using general money.

If restricted income is greater than the related expense, the remaining restricted amount should not automatically become general saving money.

It should remain restricted unless the user confirms that it can legally or practically be used for another purpose.

---

# 26. Important Rule for Contributions From Other People

There are two different situations.

### Situation A – Person Transfers Money Into the Budget

Example:

Partner transfers $350 into the shared household account.

This can be recorded as a household contribution.

### Situation B – Person Pays an Expense Directly

Example:

Partner directly pays $300 of a $600 rent bill.

The user's expense responsibility is only $300.

The partner's $300 should not also be added as income.

The application must use one method or the other for the same money.

---

# 27. Important Rule for Current Expenses

All confirmed current expenses should be included when calculating the user's starting financial position.

This includes:

- fixed expenses
- essential flexible expenses
- optional flexible expenses

The categories are used to decide which expenses may reasonably be changed.

They are not used to remove optional spending from the starting budget.

For example:

If the user currently spends $80 per week going out, that $80 must first appear in the current budget.

Only after the plan is found to be unachievable should the application suggest reducing it.

---

# 28. Important Rule for Existing Savings

Existing savings are a balance, not income.

Example:

The user already has:

- $300 for the Flight
- $200 for the PC

The $500 should reduce the remaining amount required for those goals.

It should not also be added to weekly income.

If the user has general savings that are not assigned to a goal, they should be stored as:

**Unallocated savings**

The user can later choose whether to use them.

---

# 29. Important Rule for Goal Contributions

Money contributed by another person directly toward a goal should reduce the user's required share.

Example:

Trip target:

$4,000

Partner will contribute:

$2,000

User responsibility:

$2,000

The partner's $2,000 should not also be added to the user's general income.

---

# 30. Important Rule for Transfers

Moving money between the user's own accounts does not create income or spending.

Example:

$200 transferred from everyday account to savings account.

This is:

**Transfer / allocation**

It is not:

**$200 expense**

Later moving the same $200 back into the everyday account is also not new income.

---

# 31. Important Rule for Credit Cards

A purchase should only be counted once.

Example:

The user spends $100 on groceries using a credit card.

Expense:

**Groceries = $100**

Later the user transfers $100 from their bank account to pay the credit card.

That payment should not create another $100 grocery expense.

However:

- credit card interest
- late fees
- other fees

may be separate real expenses.

---

# 32. Important Rule for Missing Information

The application must distinguish between:

- $0
- Unknown
- Missing
- Not applicable
- Paid by another person

These values have different meanings.

Example:

Electricity = $0

means the user confirms there is no electricity cost.

Electricity = Missing

means the application does not yet know the amount.

The program must not silently replace missing values with zero.

---

# 33. Important Rule for Variable Income

A missing income record should not be interpreted as zero income.

For example:

Week 1 = $500

Week 2 = $0

Week 3 = Missing

means:

- Week 2 is a confirmed zero-income week
- Week 3 has no information yet

Only confirmed values should be included according to the selected averaging method.

---

# 34. Important Rule for Time

Financial calculations must consider timing, not only averages.

Two plans with the same yearly total may still be different if:

- a large bill is due next week
- a saving goal is due next month
- income ends in three months
- an expense only exists for part of the year

Therefore, when timing matters, the application should consider:

- start date
- end date
- due date
- goal deadline
- number of remaining budgeting periods

---

# 35. Important Rule for Currency

Amounts in different currencies cannot be added directly.

If the base currency is AUD, a goal in another currency must first be converted into AUD before feasibility is calculated.

The original amount and currency should still be kept for display.

Example:

Original goal:

14,000,000 VND

Converted budgeting value:

AUD equivalent using the selected exchange rate.

The conversion should only happen once for each calculation.

---

# 36. Expected Result of the Worked Example

Before adjustment:

- General usable income: $1,350.00/week
- Restricted income: $120.00/week
- General-budget expenses: approximately $977.31/week
- Safety buffer: $50.00/week
- Available for goals: approximately $322.69/week
- Saving required: $351.25/week
- Shortfall: approximately $28.56/week
- Result: Not currently achievable

After reducing going out by $30/week:

- General-budget expenses: approximately $947.31/week
- Money after expenses: approximately $402.69/week
- Safety buffer: $50.00/week
- Available for goals: approximately $352.69/week
- Saving required: $351.25/week
- Remaining: approximately $1.44/week
- Result: Achievable, but very tight

This hand calculation will be used later to check whether the Python program produces the same result.

# Step 4 – Write the Pseudocode

## Purpose

This step describes how the Smart Savings and Spending Planner should work before writing Python code.

The pseudocode focuses on the program logic rather than Python syntax.

The main rules are:

- do not guess missing financial information
- do not count the same money twice
- only use confirmed information in important calculations
- convert money to one base currency before combining amounts
- convert income and expenses to one budgeting period before comparison
- separate general money from restricted money
- only count the user's actual share of shared expenses
- treat existing savings separately from income
- use Python for calculations
- use Gemini for conversation, extraction and explanation
- allow the user to review and correct information before calculations

---

# Main Program

START PROGRAM

Display application title and short explanation

Ask user to choose:
    base currency
    preferred budgeting period

Store settings

RUN profile setup

RUN income setup

RUN expense setup

RUN existing savings setup

RUN saving goal setup

VALIDATE all required information

NORMALISE financial data

CALCULATE current financial position

ASK user about safety buffer

CALCULATE saving goal requirements

CHECK whether the goals are achievable

IF goals are achievable
    CREATE saving plan
    DISPLAY final plan
ELSE
    RUN adjustment process
END IF

IF final plan is accepted
    SAVE plan for ongoing tracking
END IF

ALLOW user to:
    enter actual income
    enter actual expenses
    upload transaction data
    update goals
    update profile information
    review progress
    recalculate plan

END PROGRAM

---

# 1. Profile Setup

FUNCTION setup_profile

    CREATE empty user profile

    DISPLAY common profile options:
        Student
        Working
        Self-employed
        Retired
        Not currently working
        Other

    ALLOW user to select more than one option

    IF user selects Other
        ASK user to describe the situation
        SEND description to Gemini
        ASK Gemini to suggest a simple classification
        SHOW suggestion to user
        REQUIRE user confirmation
    END IF

    STORE confirmed profile information

    ASK whether any financially relevant people should be added

    WHILE user wants to add another person

        CREATE new person record

        ASK relationship:
            Partner
            Child
            Parent
            Sibling
            Grandparent
            Housemate
            Other
            More options

        IF Other or More options
            ALLOW user to select or describe:
                Stepchild
                Adopted child
                Step-parent
                Adoptive parent
                Half-sibling
                Niece/Nephew
                Ex-partner
                Other relative
                Other
        END IF

        ASK:
            Does this person live with you?

        IF age is financially relevant
            ASK age group:
                Baby
                Preschool
                Primary school
                Teen
                University-age
                Adult
                Older adult
        END IF

        ASK responsibility toward this person

        ALLOW multiple responsibility options:
            Financial support
            Care responsibility
            Shared responsibility
            Legal guardian/representative
            No financial responsibility
            Other

        IF responsibility is shared
            RECORD that another person also contributes
        END IF

        IF child relationship is selected
            ASK living/custody situation if relevant:
                Lives with me full-time
                Lives with me part-time
                Lives elsewhere
        END IF

        STORE person record

    END WHILE

    ASK whether user has pets

    IF yes
        WHILE user wants to add pets
            ASK:
                pet type
                quantity
                whether cost is shared
            STORE pet information
        END WHILE
    END IF

    DISPLAY profile summary

    ALLOW:
        Confirm
        Edit
        Add
        Remove

    RETURN confirmed profile

END FUNCTION

---

# 2. Income Setup

FUNCTION setup_income

    CREATE empty income list

    ASK user to add an income source

    WHILE user has another income source

        CREATE new income record

        ASK who receives the income

        ASK income type:
            Salary
            Casual work
            Self-employment
            Pension
            Government payment
            Child support received
            Investment income
            Other

        ASK:
            amount
            currency
            payment frequency

        Possible frequency:
            Weekly
            Fortnightly
            Monthly
            Yearly
            Irregular

        ASK income pattern:
            Regular
            Variable
            Seasonal
            Temporary
            One-off
            Irregular

        IF income is variable or irregular
            ASK whether latest period is typical

            IF latest period is not typical
                ASK for several recent confirmed periods

                FOR each period entered
                    RECORD:
                        amount
                        period date
                        status
                END FOR

                Status can be:
                    Income entered
                    Confirmed zero income
                    Missing record

                DO NOT convert missing record to zero

                CALCULATE representative average using confirmed periods only

            ELSE
                USE confirmed current amount
            END IF
        END IF

        IF income is self-employment
            ASK whether amount is:
                take-home income
                net profit
                gross revenue

            IF gross revenue
                ASK for relevant business costs
                CALCULATE net amount available to user
            END IF
        END IF

        ASK how much of the income is available to this budget:
            All
            Percentage
            Fixed amount
            None

        CALCULATE usable contribution from this source

        ASK whether income is restricted to a purpose

        IF restricted
            ASK purpose
            MARK income as restricted
        ELSE
            MARK income as general
        END IF

        ASK whether this source is expected to change:
            No expected change
            Starting soon
            Ending soon
            Expected increase
            Expected decrease
            Not sure

        IF future change is known
            RECORD effective date and expected change
        END IF

        STORE income record

    END WHILE

    DISPLAY income summary

    ALLOW user to:
        Confirm
        Edit
        Add
        Remove

    RETURN confirmed income list

END FUNCTION

---

# 3. Prevent Income Double Counting

FUNCTION validate_income_sources

    FOR each income source

        CHECK whether the money is:
            actual income
            household contribution
            restricted contribution
            one-off money
            transfer between own accounts

        IF source is an internal transfer
            DO NOT count as income
        END IF

        IF another person directly pays an expense
            DO NOT also record the same amount as income contribution
        END IF

        IF contribution is made directly to a saving goal
            DO NOT also add the same contribution to general income
        END IF

    END FOR

    RETURN cleaned income list

END FUNCTION

---

# 4. Expense Description

FUNCTION setup_expenses

    CREATE empty expense list

    ASK user to describe their current expenses naturally

    SEND expense description to Gemini

    ASK Gemini to extract only information clearly supported by the description

    Possible extracted fields:
        category
        amount
        currency
        frequency
        pattern
        person related to expense
        payer
        sharing arrangement
        user's share
        start date
        end date
        due date

    DO NOT allow Gemini to invent:
        missing amount
        missing frequency
        sharing percentage
        unknown payer
        missing dates

    STORE extracted information as unconfirmed expense records

    DISPLAY extracted expense summary to user

    FOR each extracted expense

        IF required information is missing
            MARK field as Missing or Unknown
        END IF

        ASK user to:
            Confirm
            Edit
            Remove

    END FOR

    ONLY confirmed expenses can enter the calculation stage

END FUNCTION

---

# 5. Profile-Based Missing Expense Check

FUNCTION check_missing_expenses

    BUILD a list of possible expenses based on user profile

    Example rules:

    IF user rents or has housing cost
        POSSIBLE expenses include:
            electricity
            water
            gas
            internet
            home contents insurance
    END IF

    IF user has car
        POSSIBLE expenses include:
            fuel
            registration
            insurance
            servicing
            repairs
            parking
            tolls
    END IF

    IF user is student
        POSSIBLE expenses include:
            tuition
            books
            study equipment
            software
            public transport
    END IF

    IF user has child
        POSSIBLE expenses include:
            childcare
            school costs
            activities
            clothing
            medical costs
    END IF

    IF user has baby
        POSSIBLE expenses may include:
            childcare
            nappies
            formula
            medical costs
    END IF

    IF user has pets
        POSSIBLE expenses include:
            pet food
            vet
            medication
            insurance
            grooming
    END IF

    IF user financially supports another person
        POSSIBLE expenses include:
            support payment
            care costs
            medical costs
            transport or other relevant support
    END IF

    COMPARE possible expense list with confirmed expense list

    REMOVE expenses already covered

    SHOW only possible missing expenses

    ALLOW user to:
        select applicable expense
        mark Not applicable
        mark Paid by someone else
        mark Unknown
        skip temporarily

    FOR each selected missing expense
        ASK for required details
        ADD confirmed record
    END FOR

    RETURN updated expense list

END FUNCTION

---

# 6. Expense Status

FOR every expense

    ASSIGN one status:
        Confirmed
        Estimated
        Unknown
        Not applicable
        Paid by someone else
        Missing information

    IF status is Unknown or Missing information
        DO NOT silently convert amount to zero
    END IF

    IF status is Not applicable
        EXCLUDE from calculation
    END IF

    IF Paid by someone else
        USER expense may be zero
        BUT record who pays it where relevant
    END IF

END FOR

---

# 7. Expense Classification

FUNCTION classify_expenses

    FOR each confirmed expense

        CLASSIFY as one of:
            Fixed
            Essential Flexible
            Optional Flexible

        Example:

        Fixed:
            rent
            mortgage
            required loan repayment

        Essential Flexible:
            groceries
            petrol
            utilities

        Optional Flexible:
            entertainment
            eating out
            hobbies
            shopping

        SHOW classification to user

        ALLOW user to correct classification

        STORE confirmed classification

    END FOR

    RETURN classified expenses

END FUNCTION

---

# 8. Expense Pattern

FOR each expense

    RECORD pattern where relevant:
        Regular
        Variable
        Seasonal
        Temporary
        One-off
        Irregular

    IF seasonal
        STORE relevant time periods and amounts
    END IF

    IF temporary
        STORE start date and end date
    END IF

    IF one-off
        STORE payment date
    END IF

    IF bill is monthly, quarterly or yearly
        STORE next due date where relevant
    END IF

END FOR

---

# 9. Shared Expenses

FUNCTION calculate_user_expense_share

    FOR each shared expense

        IDENTIFY:
            total amount
            user's contribution
            other contributions

        IF user's exact share is known
            USE user's actual share
        ELSE IF sharing percentage is confirmed
            CALCULATE user's share
        ELSE
            MARK sharing amount as Unknown
            ASK user for clarification
        END IF

        DO NOT count another person's direct payment as user income

    END FOR

    RETURN user expense amounts

END FUNCTION

---

# 10. Complex Expense Arrangements

FOR each expense with complex rules

    TRY to identify user's confirmed out-of-pocket amount

    IF arrangement can be calculated safely using confirmed information
        CALCULATE user's amount
    ELSE
        ASK:
            "What amount actually comes out of your budget?"

        USE confirmed out-of-pocket amount
    END IF

END FOR

---

# 11. Refunds and Reimbursements

FUNCTION process_refunds

    FOR each refund or reimbursement

        IDENTIFY related original expense if possible

        IF refund belongs to an expense
            REDUCE net cost of that expense
        END IF

        DO NOT treat normal reimbursement as recurring income

    END FOR

END FUNCTION

---

# 12. Internal Transfers

FOR each financial transaction

    IF money moves between accounts owned by the same user
        CLASSIFY as Internal Transfer
        EXCLUDE from income
        EXCLUDE from expense
    END IF

END FOR

---

# 13. Credit Card Logic

FOR each credit card transaction

    IF transaction is original purchase
        CLASSIFY by actual expense category
        COUNT purchase once
    END IF

    IF transaction is payment from bank account to credit card
        CLASSIFY as debt/account transfer
        DO NOT count original spending again
    END IF

    IF transaction is interest or fee
        COUNT as separate expense
    END IF

END FOR

---

# 14. Debt Logic

FOR each debt payment

    IF payment is required minimum or scheduled repayment
        CLASSIFY as required expense
    END IF

    IF payment is extra voluntary repayment
        ALLOW it to be treated as:
            extra debt repayment goal
            OR additional expense
        BUT not both
    END IF

END FOR

---

# 15. Existing Savings Setup

FUNCTION setup_existing_savings

    CREATE:
        allocated savings
        unallocated savings

    ASK user for existing savings

    FOR each savings amount

        ASK whether money is:
            already allocated to a goal
            unallocated general savings

        IF allocated
            LINK amount to exactly one goal
        END IF

        ENSURE same savings amount is not linked to multiple goals

    END FOR

    DO NOT count existing savings as income

    RETURN savings records

END FUNCTION

---

# 16. Saving Goal Setup

FUNCTION setup_goals

    CREATE empty goal list

    WHILE user wants to add another goal

        ASK:
            goal name
            target amount
            currency
            deadline
            priority
            deadline flexibility

        Priority options:
            Must have
            Important
            Nice to have

        Deadline options:
            Fixed
            Flexible
            No fixed deadline

        ASK whether another person contributes

        IF yes
            RECORD contribution
            CALCULATE user's target share
            DO NOT add other person's contribution to general income
        ELSE
            user's target share = full target
        END IF

        LINK any existing allocated savings

        STORE goal

    END WHILE

    RETURN goal list

END FUNCTION

---

# 17. Goal Priority Order

FUNCTION sort_goals

    PRIORITY order:
        Must have
        Important
        Nice to have

    WITHIN the same priority:
        earlier deadline comes first

    Goals with no fixed deadline come after fixed deadlines of the same priority where appropriate

    RETURN ordered goal list

END FUNCTION

---

# 18. Currency Conversion

FUNCTION convert_currency

    FOR each income, expense, savings balance and goal

        IF currency equals base currency
            keep amount unchanged
        ELSE
            GET or request exchange rate
            CONVERT amount into base currency
            KEEP original amount and currency for display
        END IF

    END FOR

    DO NOT combine different currencies before conversion

    RETURN converted financial data

END FUNCTION

---

# 19. Frequency Normalisation

FUNCTION normalise_frequency

    USE selected budgeting period

    IF budgeting period is weekly

        Weekly amount:
            keep same

        Fortnightly amount:
            divide by 2

        Monthly amount:
            multiply by 12
            divide by 52

        Yearly amount:
            divide by 52

    ELSE IF budgeting period is fortnightly

        Weekly amount:
            multiply by 2

        Fortnightly amount:
            keep same

        Monthly amount:
            multiply by 12
            divide by 26

        Yearly amount:
            divide by 26

    ELSE IF budgeting period is monthly

        Weekly amount:
            multiply by 52
            divide by 12

        Fortnightly amount:
            multiply by 26
            divide by 12

        Monthly amount:
            keep same

        Yearly amount:
            divide by 12

    END IF

    KEEP full precision internally

    ROUND for display only

END FUNCTION

---

# 20. Bills That Are Paid Less Frequently

FOR each monthly, quarterly or yearly bill

    CALCULATE normalised provision amount

    RECORD this provision as money reserved for the future bill

    WHEN actual bill payment occurs
        DO NOT count both:
            previous provisions
            and full bill payment
        as separate spending

    IF bill is due before enough provisions can accumulate
        CALCULATE catch-up amount based on:
            amount due
            amount already reserved
            time remaining until due date
    END IF

END FOR

---

# 21. Calculate Restricted Income

FUNCTION allocate_restricted_income

    FOR each restricted income source

        IDENTIFY allowed purpose

        IDENTIFY confirmed related expenses

        APPLY restricted money only to those expenses

        IF restricted money is less than related expense
            remaining expense is funded from general money
        END IF

        IF restricted money is greater than related expense
            KEEP unused amount restricted
            DO NOT automatically move it into general savings
        END IF

    END FOR

    RETURN:
        restricted allocations
        general-budget expense amounts

END FUNCTION

---

# 22. Calculate General Usable Income

FUNCTION calculate_general_income

    total_general_income = 0

    FOR each confirmed income source

        IF income is general
            ADD usable amount to total_general_income
        END IF

        IF income is restricted
            DO NOT add it to general income
        END IF

        IF income is transfer
            DO NOT add it
        END IF

    END FOR

    RETURN total_general_income

END FUNCTION

---

# 23. Calculate Current Expenses

FUNCTION calculate_total_expenses

    total_expenses = 0

    FOR each confirmed current expense

        IF expense is included in budget
            USE user's confirmed share
            USE amount after restricted support where relevant
            ADD normalised amount
        END IF

    END FOR

    INCLUDE:
        fixed expenses
        essential flexible expenses
        optional flexible expenses

    DO NOT remove optional expenses from baseline just because they could be reduced later

    RETURN total_expenses

END FUNCTION

---

# 24. Current Financial Position

general_income = CALCULATE general usable income

current_expenses = CALCULATE current confirmed expenses

money_remaining_before_goals =
    general_income - current_expenses

IF money_remaining_before_goals < 0
    DISPLAY budget deficit
    FLAG that current spending already exceeds available general income
END IF

---

# 25. Safety Buffer

FUNCTION setup_safety_buffer

    suggested_buffer =
        general_income × 5%

    DISPLAY suggested buffer

    ASK user:
        Accept suggested buffer
        Set my own amount
        No buffer

    IF user accepts suggested buffer
        selected_buffer = suggested_buffer

    ELSE IF user enters own amount
        selected_buffer = user amount

    ELSE
        selected_buffer = 0
    END IF

    IF selected_buffer > money_remaining_before_goals

        WARN user:
            current budget does not have enough room for this buffer

        ALLOW user to:
            reduce buffer
            choose no buffer
            continue reviewing budget
    END IF

    RETURN confirmed safety buffer

END FUNCTION

---

# 26. Emergency Fund vs Safety Buffer

IF user has emergency fund goal
    TREAT emergency fund as a saving goal
END IF

DO NOT confuse emergency fund goal with budgeting safety buffer

Safety buffer:
    short-term unallocated money in each budgeting period

Emergency fund:
    accumulated savings target

---

# 27. Money Available for Goals

money_available_for_goals =
    general_income
    - current_expenses
    - accepted_safety_buffer

IF result < 0
    money_available_for_goals = negative amount
    FLAG current budget as not sustainable
END IF

---

# 28. Calculate Goal Requirements

FUNCTION calculate_goal_requirements

    FOR each goal

        user's target =
            user's responsibility for goal

        allocated savings =
            savings already linked to goal

        remaining amount =
            user's target - allocated savings

        IF remaining amount < 0
            remaining amount = 0
        END IF

        IF goal has fixed or flexible deadline

            CALCULATE number of remaining budgeting periods

            IF periods remaining <= 0 AND remaining amount > 0
                MARK goal as overdue/not currently achievable by deadline
            ELSE
                required saving per period =
                    remaining amount / periods remaining
            END IF

        ELSE IF no fixed deadline
            DO NOT force arbitrary required saving amount
            ALLOW user/app to allocate remaining money after higher-priority timed goals
        END IF

    END FOR

    RETURN goal calculations

END FUNCTION

---

# 29. Feasibility Check

FUNCTION check_feasibility

    SORT goals by:
        priority
        deadline

    total_required_for_timed_goals = 0

    FOR each goal with required saving amount
        ADD required amount
    END FOR

    IF money_available_for_goals >= total_required_for_timed_goals
        status = Achievable
    ELSE
        status = Not currently achievable
        shortfall =
            total_required_for_timed_goals
            - money_available_for_goals
    END IF

    RETURN:
        status
        shortfall
        ordered goals

END FUNCTION

---

# 30. Build Achievable Plan

IF plan is achievable

    ALLOCATE required amount to:
        Must have goals first
        Important goals next
        Nice to have goals next

    IF all timed goal requirements are covered
        ALLOCATE remaining goal money to:
            ongoing goals
            no-deadline goals
            or leave unallocated
    END IF

    DISPLAY:
        income
        expenses
        safety buffer
        saving allocation per goal
        money remaining
        expected goal completion

    ASK user to accept or edit plan

END IF

---

# 31. Adjustment Process

FUNCTION find_adjustments

    shortfall = current shortfall

    CREATE list of possible adjustments

    FIRST examine Optional Flexible expenses

    SORT possible reductions by relevance

    FOR each optional flexible expense

        CREATE realistic reduction suggestion

        DO NOT reduce below zero

        SHOW:
            current amount
            suggested amount
            amount saved
            effect on shortfall

        ASK:
            Accept
            Keep current
            Enter another amount

        IF accepted
            UPDATE expense
            RECALCULATE plan

            IF plan becomes achievable
                RETURN achievable plan
            END IF
        END IF

    END FOR

    IF still not achievable

        EXAMINE Essential Flexible expenses

        Only suggest reductions that could reasonably change

        DO NOT assume essential cost can be removed

        ASK user before any change

        AFTER accepted change
            RECALCULATE
        END AFTER

    END IF

    IF still not achievable AND unallocated savings exist

        ASK whether user wants to use some unallocated savings

        IF accepted
            ALLOCATE only confirmed amount
            RECALCULATE
        END IF

    END IF

    IF still not achievable

        EXAMINE lower-priority goals

        START with:
            Nice to have
            then Important

        Possible suggestions:
            extend flexible deadline
            reduce target amount
            pause goal
            lower priority

        DO NOT automatically change a Must Have goal

        ASK user before every change

        AFTER accepted change
            RECALCULATE
        END AFTER

    END IF

    IF still not achievable
        RETURN No feasible plan
    END IF

END FUNCTION

---

# 32. Fixed Expense Rule

During automatic adjustment:

DO NOT automatically suggest reducing fixed expenses

Examples:
    rent
    mortgage
    required debt payment

User may manually edit a fixed expense if their real situation changes.

---

# 33. Recalculate After Every Accepted Change

FUNCTION recalculate_plan

    RECHECK:
        income
        expenses
        restricted allocations
        safety buffer
        existing savings
        goal requirements
        deadlines
        priority order

    CALCULATE new money available

    CALCULATE new goal requirements

    CALCULATE new shortfall or surplus

    DISPLAY updated result

END FUNCTION

---

# 34. User Rejects All Changes

IF all realistic suggestions have been rejected
AND plan is still not achievable

    DISPLAY:

    "Based on your current income, confirmed expenses,
    saving goals and the changes you are willing to make,
    I cannot find a realistic way to achieve all goals
    under the current conditions."

    SHOW:
        total shortfall
        goals affected
        deadlines affected

    OFFER:
        Change goal amount
        Change deadline
        Change priority
        Update income
        Update expenses
        Keep current plan with warning

END IF

---

# 35. Final Plan Validation

Before presenting final plan:

CHECK that:

    no income source is counted twice

    no expense is counted twice

    internal transfers are excluded

    savings transfers are excluded from spending

    credit card purchases are not duplicated by card repayment

    restricted income is only used for allowed purposes

    shared expenses use user's actual share

    contributions to goals are not also treated as general income

    existing savings are not treated as new income

    allocated savings are not assigned to multiple goals

    all calculated amounts use same base currency

    all recurring amounts use same budgeting period

    missing amounts have not been silently converted to zero

IF any validation fails
    STOP final calculation
    ASK user to correct the relevant information
END IF

---

# 36. Final Plan Output

DISPLAY:

Profile summary

Income summary:
    general usable income
    restricted income

Expense summary:
    fixed
    essential flexible
    optional flexible

Existing savings:
    allocated
    unallocated

Safety buffer

For each goal:
    target
    current allocated savings
    remaining target
    required saving per period
    expected completion date
    priority
    feasibility

DISPLAY total:
    money available
    money allocated
    remaining money

DISPLAY warning if plan is very tight

ASK user:
    Accept Plan
    Adjust Plan
    Edit Information

IF accepted
    SAVE plan as current plan
END IF

---

# 37. Ongoing Income Tracking

FUNCTION record_actual_income

    ASK budgeting period/date

    ASK actual income

    ALLOW status:
        Income entered
        Confirmed zero income
        Missing

    IF Missing
        DO NOT include as zero
    END IF

    CLASSIFY income source

    STORE actual income record

    IF income is variable
        UPDATE income history
        RECALCULATE representative income where appropriate
    END IF

END FUNCTION

---

# 38. Manual Expense Tracking

FUNCTION record_actual_expense

    ASK user for expense description

    SEND natural-language description to Gemini

    EXTRACT:
        category
        amount
        date
        payer
        other relevant information

    SHOW result to user

    REQUIRE confirmation

    CLASSIFY transaction as one of:
        Expense
        Income
        Refund
        Reimbursement
        Internal transfer
        Savings transfer
        Debt payment
        Unknown

    STORE confirmed transaction

END FUNCTION

---

# 39. CSV Transaction Tracking

FUNCTION load_transaction_csv

    ASK user to upload CSV

    TRY to read file

    IF file cannot be read
        SHOW clear error message
        STOP processing file
    END IF

    CHECK required columns

    CLEAN amounts

    HANDLE missing values

    FOR each transaction

        TRY to classify:
            expense
            income
            refund
            reimbursement
            transfer
            credit card payment
            savings transfer
            unknown

        CHECK possible duplicate

        IF duplicate is suspected
            FLAG for review
        END IF

    END FOR

    SHOW summary to user before applying transactions

    REQUIRE confirmation where necessary

    RETURN cleaned transaction data

END FUNCTION

---

# 40. Duplicate Transaction Check

FUNCTION check_duplicate

    COMPARE new transaction with existing records

    Possible indicators:
        same date
        same amount
        same description

    IF likely duplicate
        FLAG transaction

        ASK user:
            Keep
            Ignore duplicate
    END IF

END FUNCTION

---

# 41. Tracking Review

FUNCTION review_actual_performance

    FOR selected budgeting period

        CALCULATE:
            planned income
            actual income

            planned spending
            actual spending

            planned saving
            actual saving

        FOR each expense category
            CALCULATE difference
        END FOR

        FOR each saving goal
            CALCULATE:
                current balance
                expected balance
                progress difference
        END FOR

    DISPLAY:
        income variance
        spending variance
        categories over budget
        categories under budget
        goal progress

END FUNCTION

---

# 42. Replanning After Actual Results

IF actual income or spending is meaningfully different from plan

    CALCULATE updated financial position

    CHECK whether current saving plan is still achievable

    IF still achievable
        SHOW updated progress
    ELSE
        SHOW effect on affected goals

        RUN adjustment process again
    END IF

END IF

---

# 43. Gemini Explanation

After Python calculates a result:

SEND structured calculation result to Gemini

ASK Gemini to explain result in simple budgeting language

Gemini may explain:

    what changed
    why a goal is achievable or not achievable
    which spending category affects the plan
    what options the user can consider

Gemini must not change the calculated numbers.

Python calculation remains the source of truth.

---

# 44. Unclear Input

IF user input is unclear

    Gemini asks a clarification question

    DO NOT guess the financial value

    WAIT for confirmation before calculation

END IF

---

# 45. Off-Topic Input

IF user asks something unrelated to personal budgeting or saving

    Gemini responds politely

    GUIDE user back to:
        budgeting
        saving
        income
        expenses
        financial goals

END IF

---

# 46. Error Handling

IF user enters invalid number
    SHOW:
        what is wrong
        what input is expected
END IF

IF amount is negative where negative values are not allowed
    ASK user to correct it
END IF

IF deadline occurs before current date
    WARN user
    ASK whether:
        deadline is incorrect
        goal is overdue
END IF

IF currency conversion fails
    DO NOT calculate using an invented rate
    ASK user to retry or enter a confirmed rate
END IF

IF Gemini cannot confidently extract information
    MARK field as Unknown
    ASK user
END IF

IF API is unavailable
    SHOW understandable error
    DO NOT crash application
END IF

---

# 47. Final Logic Rules

The following rules should remain true throughout the application.

1. One amount should not be counted twice.

2. Missing information is not the same as zero.

3. Existing savings are not new income.

4. Internal transfers are not income or spending.

5. Only the user's real share of an expense reduces their budget.

6. Restricted money stays restricted unless the user confirms otherwise.

7. Different currencies must be converted before being combined.

8. Different payment frequencies must be normalised before being compared.

9. Current optional spending is included in the starting budget before reductions are suggested.

10. Fixed and required expenses are handled before optional saving goals.

11. Goal priority affects allocation but cannot create money that does not exist.

12. A Must Have goal can still be unachievable.

13. Gemini can interpret information but must not invent financial values.

14. Important information interpreted by Gemini must be confirmed by the user.

15. Python performs the final financial calculations.

16. The user keeps control over changes to their spending plan.

17. If no realistic solution exists, the application should say so instead of producing an impossible plan.

END

## Design Note – Goal Lifecycle

During development, I decided that saving goals should continue to be managed after the initial plan is created.

A goal can have a status such as:

- Active
- Completed
- Paused
- Cancelled

Users will be able to add new goals or update existing goals while using the application.

When a goal is completed, the application should:

1. mark the goal as completed
2. congratulate the user
3. stop allocating future money to that goal
4. allow the released money to be allocated to another goal, kept as savings, or used for a new goal
5. recalculate the saving plan

Completed goals should remain in the user's goal history rather than being deleted.

This will be incorporated into the final version of the earlier planning steps after the first working draft is complete.

# Step 5 – Convert the Pseudocode to Python

## Step 5A – Core Financial Calculations

I will build the program in small functions instead of writing the whole application at once.

The first functions will handle the main calculations that are needed by the rest of the application.

I will begin with frequency normalisation so that income and expenses with different payment frequencies can be compared using the same budgeting period.

In [ ]:
def normalise_frequency(amount, frequency, budget_period="weekly"):
    """
    Convert an amount into the selected budgeting period.
    """

    if amount < 0:
        raise ValueError("Amount cannot be negative.")

    frequency = frequency.lower()
    budget_period = budget_period.lower()

    # Convert the original amount to a yearly amount first
    if frequency == "weekly":
        yearly_amount = amount * 52

    elif frequency == "fortnightly":
        yearly_amount = amount * 26

    elif frequency == "monthly":
        yearly_amount = amount * 12

    elif frequency == "yearly":
        yearly_amount = amount

    else:
        raise ValueError("Frequency must be weekly, fortnightly, monthly or yearly.")

    # Convert the yearly amount into the selected budgeting period
    if budget_period == "weekly":
        return yearly_amount / 52

    elif budget_period == "fortnightly":
        return yearly_amount / 26

    elif budget_period == "monthly":
        return yearly_amount / 12

    else:
        raise ValueError("Budget period must be weekly, fortnightly or monthly.")

In [ ]:
print(normalise_frequency(60, "monthly", "weekly"))
print(normalise_frequency(1000, "weekly", "monthly"))
print(normalise_frequency(1200, "yearly", "monthly"))

13.846153846153847
4333.333333333333
100.0

In [ ]:
def calculate_average_income(income_records):
    """
    Calculate the average income using confirmed records only.
    Missing records are ignored.
    """

    confirmed_amounts = []

    for record in income_records:
        if record["status"] == "entered":
            confirmed_amounts.append(record["amount"])

        elif record["status"] == "zero":
            confirmed_amounts.append(0)

        elif record["status"] == "missing":
            continue

    if len(confirmed_amounts) == 0:
        raise ValueError("No confirmed income records available.")

    return sum(confirmed_amounts) / len(confirmed_amounts)

In [ ]:
income_records = [
    {"amount": 450, "status": "entered"},
    {"amount": 300, "status": "entered"},
    {"amount": 0, "status": "zero"},
    {"amount": None, "status": "missing"}
]

print(calculate_average_income(income_records))

250.0

In [ ]:
def calculate_user_share(total_amount, share_percent=100):
    """
    Calculate the user's share of a shared expense.
    """

    if total_amount < 0:
        raise ValueError("Expense amount cannot be negative.")

    if share_percent < 0 or share_percent > 100:
        raise ValueError("Share percentage must be between 0 and 100.")

    user_share = total_amount * share_percent / 100

    return user_share

In [ ]:
print(calculate_user_share(600, 50))
print(calculate_user_share(600, 37))
print(calculate_user_share(300))

300.0
222.0
300.0

In [ ]:
def calculate_available_income(amount, availability_type="all", availability_value=None):
    """
    Calculate how much of an income source is available to the budget.
    """

    if amount < 0:
        raise ValueError("Income amount cannot be negative.")

    availability_type = availability_type.lower()

    if availability_type == "all":
        return amount

    elif availability_type == "percent":
        if availability_value is None:
            raise ValueError("Please provide an availability percentage.")

        if availability_value < 0 or availability_value > 100:
            raise ValueError("Percentage must be between 0 and 100.")

        return amount * availability_value / 100

    elif availability_type == "fixed":
        if availability_value is None:
            raise ValueError("Please provide a fixed available amount.")

        if availability_value < 0 or availability_value > amount:
            raise ValueError("Fixed available amount must be between 0 and the income amount.")

        return availability_value

    elif availability_type == "none":
        return 0

    else:
        raise ValueError("Availability type must be all, percent, fixed or none.")

In [ ]:
print(calculate_available_income(1000, "all"))
print(calculate_available_income(1000, "percent", 40))
print(calculate_available_income(1000, "fixed", 300))
print(calculate_available_income(1000, "none"))

1000
400.0
300
0

In [ ]:
def calculate_income_totals(income_sources, budget_period="weekly"):
    """
    Calculate general and restricted usable income
    in the selected budgeting period.
    """

    general_income = 0
    restricted_income = 0

    for source in income_sources:

        # Work out how much of this income is actually available
        available_amount = calculate_available_income(
            source["amount"],
            source.get("availability_type", "all"),
            source.get("availability_value")
        )

        # Convert it into the selected budgeting period
        normalised_amount = normalise_frequency(
            available_amount,
            source["frequency"],
            budget_period
        )

        # Keep restricted money separate from general money
        if source.get("restricted", False):
            restricted_income += normalised_amount
        else:
            general_income += normalised_amount

    return general_income, restricted_income

In [ ]:
income_sources = [
    {
        "name": "My salary",
        "amount": 1000,
        "frequency": "weekly",
        "availability_type": "all",
        "restricted": False
    },
    {
        "name": "Partner income",
        "amount": 1000,
        "frequency": "weekly",
        "availability_type": "fixed",
        "availability_value": 350,
        "restricted": False
    },
    {
        "name": "Child support",
        "amount": 120,
        "frequency": "weekly",
        "availability_type": "all",
        "restricted": True
    }
]

general_income, restricted_income = calculate_income_totals(income_sources)

print("General income:", general_income)
print("Restricted income:", restricted_income)

General income: 1350.0
Restricted income: 120.0

In [ ]:
def apply_restricted_income(expense_amount, restricted_amount):
    """
    Apply restricted income to a related expense.

    Returns:
        amount_paid_by_restricted_income
        amount_left_for_general_budget
        restricted_income_left
    """

    if expense_amount < 0 or restricted_amount < 0:
        raise ValueError("Amounts cannot be negative.")

    amount_used = min(expense_amount, restricted_amount)

    general_budget_amount = expense_amount - amount_used

    restricted_left = restricted_amount - amount_used

    return amount_used, general_budget_amount, restricted_left

In [ ]:
used, general_cost, restricted_left = apply_restricted_income(220, 120)

print("Restricted income used:", used)
print("General budget pays:", general_cost)
print("Restricted income left:", restricted_left)

Restricted income used: 120
General budget pays: 100
Restricted income left: 0

In [ ]:
used, general_cost, restricted_left = apply_restricted_income(100, 150)

print("Restricted income used:", used)
print("General budget pays:", general_cost)
print("Restricted income left:", restricted_left)

Restricted income used: 100
General budget pays: 0
Restricted income left: 50

In [ ]:
def calculate_total_expenses(expenses, budget_period="weekly"):
    """
    Calculate the user's total confirmed expenses
    in the selected budgeting period.
    """

    total_expenses = 0

    for expense in expenses:

        # Ignore expenses that should not be counted
        if expense.get("status") in ["not_applicable", "paid_by_other", "missing", "unknown"]:
            continue

        # Calculate the user's share
        user_amount = calculate_user_share(
            expense["amount"],
            expense.get("share_percent", 100)
        )

        # Convert to selected budgeting period
        normalised_amount = normalise_frequency(
            user_amount,
            expense["frequency"],
            budget_period
        )

        total_expenses += normalised_amount

    return total_expenses

In [ ]:
expenses = [
    {
        "name": "Rent",
        "amount": 520,
        "frequency": "weekly",
        "share_percent": 100,
        "status": "confirmed"
    },
    {
        "name": "Groceries",
        "amount": 170,
        "frequency": "weekly",
        "share_percent": 100,
        "status": "confirmed"
    },
    {
        "name": "Phone",
        "amount": 60,
        "frequency": "monthly",
        "share_percent": 100,
        "status": "confirmed"
    },
    {
        "name": "Electricity",
        "amount": 180,
        "frequency": "monthly",
        "share_percent": 100,
        "status": "confirmed"
    },
    {
        "name": "Streaming",
        "amount": 30,
        "frequency": "monthly",
        "share_percent": 100,
        "status": "confirmed"
    }
]

print(calculate_total_expenses(expenses))

752.3076923076923

In [ ]:
def calculate_money_remaining(general_income, total_expenses):
    """
    Calculate how much general-purpose money remains
    after current expenses.
    """

    if general_income < 0:
        raise ValueError("General income cannot be negative.")

    if total_expenses < 0:
        raise ValueError("Total expenses cannot be negative.")

    return general_income - total_expenses

In [ ]:
general_income = 1350
total_expenses = 977.3076923076923

money_remaining = calculate_money_remaining(
    general_income,
    total_expenses
)

print("Money remaining:", money_remaining)

Money remaining: 372.69230769230774

In [ ]:
def calculate_suggested_buffer(general_income, buffer_percent=5):
    """
    Suggest a safety buffer as a percentage of general usable income.
    """

    if general_income < 0:
        raise ValueError("General income cannot be negative.")

    if buffer_percent < 0 or buffer_percent > 100:
        raise ValueError("Buffer percentage must be between 0 and 100.")

    return general_income * buffer_percent / 100

In [ ]:
suggested_buffer = calculate_suggested_buffer(1350)

print("Suggested safety buffer:", suggested_buffer)

Suggested safety buffer: 67.5

In [ ]:
def calculate_money_for_goals(money_remaining, buffer_amount):
    """
    Calculate money available for saving goals
    after the confirmed safety buffer.
    """

    if buffer_amount < 0:
        raise ValueError("Buffer amount cannot be negative.")

    if buffer_amount > max(money_remaining, 0):
        raise ValueError("Safety buffer is larger than the money available.")

    return money_remaining - buffer_amount

In [ ]:
money_for_goals = calculate_money_for_goals(
    money_remaining,
    50
)

print("Money available for goals:", money_for_goals)

Money available for goals: 322.69230769230774

In [ ]:
def calculate_goal_requirement(target_amount, already_saved, periods_left):
    """
    Calculate the remaining amount and required saving
    per budgeting period for a saving goal.
    """

    if target_amount < 0 or already_saved < 0:
        raise ValueError("Goal amounts cannot be negative.")

    remaining_amount = max(target_amount - already_saved, 0)

    # Goal is already completed
    if remaining_amount == 0:
        return 0, 0

    if periods_left <= 0:
        raise ValueError("Periods left must be greater than 0 for an incomplete goal.")

    required_per_period = remaining_amount / periods_left

    return remaining_amount, required_per_period

In [ ]:
flight_remaining, flight_weekly = calculate_goal_requirement(
    1500, 300, 10
)

pc_remaining, pc_weekly = calculate_goal_requirement(
    3500, 200, 16
)

bag_remaining, bag_weekly = calculate_goal_requirement(
    400, 0, 16
)

print("Flight:", flight_remaining, flight_weekly)
print("PC:", pc_remaining, pc_weekly)
print("Bag:", bag_remaining, bag_weekly)

Flight: 1200 120.0
PC: 3300 206.25
Bag: 400 25.0

In [ ]:
def check_goal_feasibility(money_for_goals, required_amounts):
    """
    Check whether the available money is enough
    to cover all saving goal requirements.
    """

    if money_for_goals < 0:
        raise ValueError("Money available for goals cannot be negative.")

    total_required = sum(required_amounts)

    difference = money_for_goals - total_required

    if difference >= 0:
        status = "achievable"
        surplus = difference
        shortfall = 0
    else:
        status = "not achievable"
        surplus = 0
        shortfall = abs(difference)

    return total_required, status, surplus, shortfall

In [ ]:
required_amounts = [
    flight_weekly,
    pc_weekly,
    bag_weekly
]

total_required, status, surplus, shortfall = check_goal_feasibility(
    money_for_goals,
    required_amounts
)

print("Total saving required:", total_required)
print("Status:", status)
print("Surplus:", surplus)
print("Shortfall:", shortfall)

Total saving required: 351.25
Status: not achievable
Surplus: 0
Shortfall: 28.557692307692264

In [ ]:
def suggest_expense_reduction(current_amount, shortfall):
    """
    Suggest how much to reduce an optional expense
    to cover the current shortfall.
    """

    if current_amount < 0 or shortfall < 0:
        raise ValueError("Amounts cannot be negative.")

    reduction = min(current_amount, shortfall)

    suggested_amount = current_amount - reduction

    return reduction, suggested_amount

In [ ]:
reduction, suggested_amount = suggest_expense_reduction(
    80,
    shortfall
)

print("Suggested reduction:", reduction)
print("Suggested new amount:", suggested_amount)

Suggested reduction: 28.557692307692264
Suggested new amount: 51.442307692307736

In [ ]:
def recalculate_after_reduction(
    general_income,
    total_expenses,
    buffer_amount,
    required_amounts,
    reduction_amount
):
    """
    Recalculate the budget after the user accepts
    an expense reduction.
    """

    if reduction_amount < 0:
        raise ValueError("Reduction amount cannot be negative.")

    if reduction_amount > total_expenses:
        raise ValueError("Reduction cannot be greater than total expenses.")

    new_total_expenses = total_expenses - reduction_amount

    new_money_remaining = calculate_money_remaining(
        general_income,
        new_total_expenses
    )

    new_money_for_goals = calculate_money_for_goals(
        new_money_remaining,
        buffer_amount
    )

    total_required, status, surplus, shortfall = check_goal_feasibility(
        new_money_for_goals,
        required_amounts
    )

    return (
        new_total_expenses,
        new_money_remaining,
        new_money_for_goals,
        status,
        surplus,
        shortfall
    )

In [ ]:
results = recalculate_after_reduction(
    1350,
    977.3076923076923,
    50,
    required_amounts,
    30
)

print("New expenses:", results[0])
print("New money remaining:", results[1])
print("New money for goals:", results[2])
print("Status:", results[3])
print("Surplus:", results[4])
print("Shortfall:", results[5])

New expenses: 947.3076923076923
New money remaining: 402.69230769230774
New money for goals: 352.69230769230774
Status: achievable
Surplus: 1.442307692307736
Shortfall: 0

In [ ]:
def sort_goals_by_priority(goals):
    """
    Sort active goals by:
    1. Priority
    2. Nearest deadline / fewest periods left
    """

    priority_order = {
        "must have": 1,
        "important": 2,
        "nice to have": 3
    }

    active_goals = []

    for goal in goals:
        if goal.get("status", "active") == "active":
            active_goals.append(goal)

    def goal_sort_key(goal):
        priority_rank = priority_order.get(
            goal["priority"].lower(),
            99
        )

        periods_left = goal.get("periods_left")

        # Goals with no deadline go after timed goals
        if periods_left is None:
            periods_left = 999999

        return priority_rank, periods_left

    return sorted(active_goals, key=goal_sort_key)

In [ ]:
goals = [
    {
        "name": "Bag",
        "priority": "Nice to have",
        "periods_left": 16,
        "status": "active"
    },
    {
        "name": "PC",
        "priority": "Important",
        "periods_left": 16,
        "status": "active"
    },
    {
        "name": "Flight",
        "priority": "Must have",
        "periods_left": 10,
        "status": "active"
    },
    {
        "name": "Old Phone",
        "priority": "Must have",
        "periods_left": 2,
        "status": "completed"
    }
]

sorted_goals = sort_goals_by_priority(goals)

for goal in sorted_goals:
    print(goal["name"], "-", goal["priority"])

Flight - Must have
PC - Important
Bag - Nice to have

In [ ]:
def check_goal_completion(goal):
    """
    Check whether a saving goal has reached its target
    without changing paused or cancelled goals back to active.
    """

    target_amount = goal["target_amount"]
    current_saved = goal["current_saved"]

    if target_amount < 0 or current_saved < 0:
        raise ValueError("Goal amounts cannot be negative.")

    # Do not reactivate cancelled goals
    if goal.get("status") == "cancelled":
        return goal, f"{goal['name']} is cancelled."

    if current_saved >= target_amount:
        goal["status"] = "completed"

        message = (
            f"Congratulations! You reached your "
            f"{goal['name']} goal of ${target_amount:.2f}."
        )

    else:
        remaining = target_amount - current_saved

        # Keep paused goals paused
        if goal.get("status") != "paused":
            goal["status"] = "active"

        message = (
            f"{goal['name']} still needs "
            f"${remaining:.2f}."
        )

    return goal, message

In [ ]:
def update_goal_progress(goal, amount_saved):
    """
    Add new savings to a goal and check its status.
    """

    if amount_saved < 0:
        raise ValueError("Saved amount cannot be negative.")

    if goal.get("status") == "cancelled":
        raise ValueError("Cannot add savings to a cancelled goal.")

    if goal.get("status") == "completed":
        return goal, f"{goal['name']} is already completed."

    goal["current_saved"] += amount_saved

    return check_goal_completion(goal)

In [ ]:
bag_goal = {
    "name": "Bag",
    "target_amount": 400,
    "current_saved": 250,
    "status": "active"
}

updated_goal, message = update_goal_progress(
    bag_goal,
    100
)

print("Saved:", updated_goal["current_saved"])
print("Status:", updated_goal["status"])
print(message)

Saved: 350
Status: active
Bag still needs $50.00.

In [ ]:
updated_goal, message = update_goal_progress(
    updated_goal,
    50
)

print("Saved:", updated_goal["current_saved"])
print("Status:", updated_goal["status"])
print(message)

Saved: 400
Status: completed
Congratulations! You reached your Bag goal of $400.00.

## Design Note – Parallel Goal Saving

Saving goals should normally run at the same time.

Each active goal receives the minimum amount needed per budgeting period to meet its deadline.

Priority does not mean that one goal must be completed before saving for another goal.

Priority is mainly used when:

- there is not enough money to fully fund every goal
- extra money is available and the user wants to complete a higher-priority goal earlier
- the application needs to suggest which lower-priority goal could be delayed or adjusted

If enough money is available, all active goals should receive their required saving amount during the same budgeting period.

In [ ]:
def allocate_goal_savings(goals, money_for_goals):
    """
    Allocate the required saving amount to all active goals
    when enough money is available.
    """

    if money_for_goals < 0:
        raise ValueError("Money available for goals cannot be negative.")

    active_goals = []

    for goal in goals:
        if goal.get("status", "active") == "active":
            active_goals.append(goal)

    total_required = 0

    for goal in active_goals:
        total_required += goal["required_per_period"]

    # Not enough money for all goals
    if money_for_goals < total_required:
        shortfall = total_required - money_for_goals

        return {
            "status": "not achievable",
            "allocations": {},
            "extra_money": 0,
            "shortfall": shortfall
        }

    # Enough money: fund all goals at the same time
    allocations = {}

    for goal in active_goals:
        allocations[goal["name"]] = goal["required_per_period"]

    extra_money = money_for_goals - total_required

    return {
        "status": "achievable",
        "allocations": allocations,
        "extra_money": extra_money,
        "shortfall": 0
    }

In [ ]:
goals = [
    {
        "name": "Flight",
        "required_per_period": 120,
        "priority": "Must have",
        "status": "active"
    },
    {
        "name": "PC",
        "required_per_period": 206.25,
        "priority": "Important",
        "status": "active"
    },
    {
        "name": "Bag",
        "required_per_period": 25,
        "priority": "Nice to have",
        "status": "active"
    }
]

allocation_result = allocate_goal_savings(
    goals,
    352.69230769230774
)

print("Status:", allocation_result["status"])
print("Allocations:", allocation_result["allocations"])
print("Extra money:", allocation_result["extra_money"])
print("Shortfall:", allocation_result["shortfall"])

Status: achievable
Allocations: {'Flight': 120, 'PC': 206.25, 'Bag': 25}
Extra money: 1.442307692307736
Shortfall: 0

In [ ]:
def allocate_extra_to_priority_goals(goals, allocations, extra_money):
    """
    Add extra money to active goals by priority.

    Extra money is only allocated after every goal has
    already received its required amount for the period.
    """

    if extra_money < 0:
        raise ValueError("Extra money cannot be negative.")

    updated_allocations = allocations.copy()

    sorted_goals = sort_goals_by_priority(goals)

    for goal in sorted_goals:

        if extra_money <= 0:
            break

        current_allocation = updated_allocations.get(goal["name"], 0)

        remaining_amount = goal["remaining_amount"]

        # Do not allocate more than the goal still needs
        extra_needed = max(
            remaining_amount - current_allocation,
            0
        )

        extra_for_goal = min(extra_money, extra_needed)

        updated_allocations[goal["name"]] = (
            current_allocation + extra_for_goal
        )

        extra_money -= extra_for_goal

    return updated_allocations, extra_money

In [ ]:
goals = [
    {
        "name": "Flight",
        "priority": "Must have",
        "periods_left": 10,
        "remaining_amount": 1200,
        "status": "active"
    },
    {
        "name": "PC",
        "priority": "Important",
        "periods_left": 16,
        "remaining_amount": 3300,
        "status": "active"
    },
    {
        "name": "Bag",
        "priority": "Nice to have",
        "periods_left": 16,
        "remaining_amount": 400,
        "status": "active"
    }
]

allocations = {
    "Flight": 120,
    "PC": 206.25,
    "Bag": 25
}

updated_allocations, money_left = allocate_extra_to_priority_goals(
    goals,
    allocations,
    1.442307692307736
)

print("Updated allocations:", updated_allocations)
print("Money still unallocated:", money_left)

Updated allocations: {'Flight': 121.44230769230774, 'PC': 206.25, 'Bag': 25}
Money still unallocated: 0.0

In [ ]:
def apply_goal_allocations(goals, allocations):
    """
    Apply this period's allocations to active goals.

    If an allocation is larger than the amount still needed,
    the unused money is returned instead of disappearing.
    """

    messages = []
    unused_money = 0

    for goal in goals:

        if goal.get("status", "active") != "active":
            continue

        amount = allocations.get(goal["name"], 0)

        if amount < 0:
            raise ValueError("Goal allocation cannot be negative.")

        remaining = max(
            goal["target_amount"] - goal["current_saved"],
            0
        )

        actual_amount = min(amount, remaining)

        # Money that was allocated but no longer needed
        unused_money += amount - actual_amount

        goal["current_saved"] += actual_amount

        updated_goal, message = check_goal_completion(goal)

        messages.append(message)

    return goals, messages, unused_money

In [ ]:
tracking_goals = [
    {
        "name": "Bag",
        "target_amount": 400,
        "current_saved": 390,
        "status": "active"
    }
]

period_allocations = {
    "Bag": 25
}

tracking_goals, messages, unused_money = apply_goal_allocations(
    tracking_goals,
    period_allocations
)

print("Saved:", tracking_goals[0]["current_saved"])
print("Status:", tracking_goals[0]["status"])
print("Unused money:", unused_money)

for message in messages:
    print(message)

Saved: 400
Status: completed
Unused money: 15
Congratulations! You reached your Bag goal of $400.00.

In [ ]:
def reallocate_unused_money(goals, unused_money):
    """
    Move unused money to other active goals by priority.

    Money will not be added beyond a goal's target.
    Any money that still cannot be allocated is returned.
    """

    if unused_money < 0:
        raise ValueError("Unused money cannot be negative.")

    messages = []

    sorted_goals = sort_goals_by_priority(goals)

    for goal in sorted_goals:

        if unused_money <= 0:
            break

        remaining = max(
            goal["target_amount"] - goal["current_saved"],
            0
        )

        if remaining == 0:
            continue

        amount_to_add = min(unused_money, remaining)

        goal["current_saved"] += amount_to_add
        unused_money -= amount_to_add

        updated_goal, message = check_goal_completion(goal)

        messages.append(
            f"${amount_to_add:.2f} was moved to {goal['name']}. "
            + message
        )

    return goals, unused_money, messages

In [ ]:
goals = [
    {
        "name": "Flight",
        "target_amount": 1500,
        "current_saved": 500,
        "priority": "Must have",
        "periods_left": 8,
        "status": "active"
    },
    {
        "name": "PC",
        "target_amount": 3500,
        "current_saved": 700,
        "priority": "Important",
        "periods_left": 14,
        "status": "active"
    },
    {
        "name": "Bag",
        "target_amount": 400,
        "current_saved": 400,
        "priority": "Nice to have",
        "periods_left": 0,
        "status": "completed"
    }
]

goals, unused_money, messages = reallocate_unused_money(
    goals,
    15
)

for goal in goals:
    print(goal["name"], "-", goal["current_saved"], "-", goal["status"])

print("Money still unallocated:", unused_money)

for message in messages:
    print(message)

Flight - 515 - active
PC - 700 - active
Bag - 400 - completed
Money still unallocated: 0
$15.00 was moved to Flight. Flight still needs $985.00.

In [ ]:
def keep_as_unallocated_savings(unallocated_savings, unused_money):
    """
    Add unused money to general unallocated savings.
    """

    if unallocated_savings < 0 or unused_money < 0:
        raise ValueError("Savings amounts cannot be negative.")

    return unallocated_savings + unused_money

In [ ]:
unallocated_savings = 200
unused_money = 15

unallocated_savings = keep_as_unallocated_savings(
    unallocated_savings,
    unused_money
)

print("Unallocated savings:", unallocated_savings)

Unallocated savings: 215

In [ ]:
def add_goal(
    goals,
    name,
    target_amount,
    current_saved=0,
    priority="Important",
    periods_left=None
):
    """
    Add a new saving goal while the plan is already running.
    """

    if target_amount <= 0:
        raise ValueError("Target amount must be greater than 0.")

    if current_saved < 0:
        raise ValueError("Current savings cannot be negative.")

    valid_priorities = [
        "must have",
        "important",
        "nice to have"
    ]

    if priority.lower() not in valid_priorities:
        raise ValueError(
            "Priority must be Must have, Important or Nice to have."
        )

    # Goal names must be unique
    for goal in goals:
        if goal["name"].lower() == name.lower():
            raise ValueError("A goal with this name already exists.")

    if current_saved >= target_amount:
        status = "completed"
    else:
        status = "active"

    new_goal = {
        "name": name,
        "target_amount": target_amount,
        "current_saved": current_saved,
        "priority": priority,
        "periods_left": periods_left,
        "status": status
    }

    goals.append(new_goal)

    return goals

In [ ]:
goals = add_goal(
    goals,
    "Japan Trip",
    2000,
    300,
    "Important",
    20
)

for goal in goals:
    print(
        goal["name"],
        "- target:",
        goal["target_amount"],
        "- saved:",
        goal["current_saved"],
        "- status:",
        goal["status"]
    )

Flight - target: 1500 - saved: 515 - status: active
PC - target: 3500 - saved: 700 - status: active
Bag - target: 400 - saved: 400 - status: completed
Japan Trip - target: 2000 - saved: 300 - status: active

In [ ]:
def change_goal_status(goals, goal_name, new_status):
    """
    Change a goal between active and paused.
    """

    valid_statuses = [
        "active",
        "paused"
    ]

    if new_status.lower() not in valid_statuses:
        raise ValueError(
            "Status must be active or paused."
        )

    for goal in goals:

        if goal["name"].lower() == goal_name.lower():

            if goal.get("status") == "completed":
                raise ValueError(
                    "A completed goal cannot be changed back."
                )

            if goal.get("status") == "cancelled":
                raise ValueError(
                    "A cancelled goal cannot be changed."
                )

            goal["status"] = new_status.lower()

            return goals

    raise ValueError("Goal not found.")

In [ ]:
# Repair goals if it was accidentally changed into a tuple
if isinstance(goals, tuple):
    goals = goals[0]

In [ ]:
def cancel_goal(goals, goal_name):
    """
    Cancel a goal and release the savings
    currently stored in that goal.
    """

    for goal in goals:

        if goal["name"].lower() == goal_name.lower():

            if goal.get("status") == "completed":
                raise ValueError(
                    "A completed goal should stay in history."
                )

            if goal.get("status") == "cancelled":
                raise ValueError(
                    "This goal is already cancelled."
                )

            released_money = goal["current_saved"]

            goal["current_saved"] = 0
            goal["status"] = "cancelled"

            return goals, released_money

    raise ValueError("Goal not found.")

In [ ]:
def edit_goal(
    goals,
    goal_name,
    new_target=None,
    new_priority=None,
    new_periods_left=None
):
    """
    Edit an active or paused goal.

    Returns:
        updated goals
        money released if target is reduced below current savings
    """

    valid_priorities = [
        "must have",
        "important",
        "nice to have"
    ]

    for goal in goals:

        if goal["name"].lower() == goal_name.lower():

            if goal.get("status") == "completed":
                raise ValueError(
                    "Completed goals should stay in history. "
                    "Create a new goal instead."
                )

            if goal.get("status") == "cancelled":
                raise ValueError("Cannot edit a cancelled goal.")

            released_money = 0

            # Change target
            if new_target is not None:

                if new_target <= 0:
                    raise ValueError(
                        "Target amount must be greater than 0."
                    )

                goal["target_amount"] = new_target

                # User has already saved more than the new target
                if goal["current_saved"] > new_target:

                    released_money = (
                        goal["current_saved"] - new_target
                    )

                    goal["current_saved"] = new_target
                    goal["status"] = "completed"

                elif goal["current_saved"] == new_target:
                    goal["status"] = "completed"

            # Change priority
            if new_priority is not None:

                if new_priority.lower() not in valid_priorities:
                    raise ValueError(
                        "Priority must be Must have, "
                        "Important or Nice to have."
                    )

                goal["priority"] = new_priority

            # Change deadline / periods left
            if new_periods_left is not None:

                if new_periods_left <= 0:
                    raise ValueError(
                        "Periods left must be greater than 0."
                    )

                goal["periods_left"] = new_periods_left

            return goals, released_money

    raise ValueError("Goal not found.")

In [ ]:
def update_goal_requirements(goals):
    """
    Recalculate remaining amount and required saving
    for each active goal.
    """

    for goal in goals:

        if goal.get("status") != "active":
            goal["remaining_amount"] = max(
                goal["target_amount"] - goal["current_saved"],
                0
            )
            goal["required_per_period"] = 0
            continue

        remaining_amount = max(
            goal["target_amount"] - goal["current_saved"],
            0
        )

        goal["remaining_amount"] = remaining_amount

        periods_left = goal.get("periods_left")

        if remaining_amount == 0:
            goal["required_per_period"] = 0
            goal["status"] = "completed"

        elif periods_left is None:
            goal["required_per_period"] = 0

        elif periods_left <= 0:
            goal["required_per_period"] = None

        else:
            goal["required_per_period"] = (
                remaining_amount / periods_left
            )

    return goals

In [ ]:
goals = change_goal_status(
    goals,
    "Japan Trip",
    "active"
)

goals = update_goal_requirements(goals)

for goal in goals:
    print(
        goal["name"],
        "- remaining:",
        goal.get("remaining_amount"),
        "- required:",
        goal.get("required_per_period"),
        "- status:",
        goal["status"]
    )

Flight - remaining: 985 - required: 123.125 - status: active
PC - remaining: 2800 - required: 200.0 - status: active
Bag - remaining: 0 - required: 0 - status: completed
Japan Trip - remaining: 1700 - required: 85.0 - status: active

In [ ]:
def check_updated_plan(goals, money_for_goals):
    """
    Recheck whether the current money available
    is enough for all active timed goals.
    """

    if money_for_goals < 0:
        raise ValueError("Money available for goals cannot be negative.")

    total_required = 0
    overdue_goals = []

    for goal in goals:

        if goal.get("status") != "active":
            continue

        required = goal.get("required_per_period")

        # None means the goal has money remaining
        # but no valid periods left
        if required is None:
            overdue_goals.append(goal["name"])
            continue

        total_required += required

    if overdue_goals:
        return {
            "status": "needs attention",
            "total_required": total_required,
            "surplus": 0,
            "shortfall": 0,
            "overdue_goals": overdue_goals
        }

    difference = money_for_goals - total_required

    if difference >= 0:
        status = "achievable"
        surplus = difference
        shortfall = 0
    else:
        status = "not achievable"
        surplus = 0
        shortfall = abs(difference)

    return {
        "status": status,
        "total_required": total_required,
        "surplus": surplus,
        "shortfall": shortfall,
        "overdue_goals": []
    }

In [ ]:
updated_plan = check_updated_plan(
    goals,
    352.69230769230774
)

print("Status:", updated_plan["status"])
print("Total required:", updated_plan["total_required"])
print("Surplus:", updated_plan["surplus"])
print("Shortfall:", updated_plan["shortfall"])
print("Overdue goals:", updated_plan["overdue_goals"])

Status: not achievable
Total required: 408.125
Surplus: 0
Shortfall: 55.432692307692264
Overdue goals: []

In [ ]:
def find_adjustable_goal(goals):
    """
    Find the lowest-priority active goal that could be adjusted.
    Nice to have goals are considered before Important goals.
    Must have goals are not automatically suggested for adjustment.
    """

    priority_order = {
        "nice to have": 1,
        "important": 2,
        "must have": 3
    }

    adjustable_goals = []

    for goal in goals:

        if goal.get("status") != "active":
            continue

        if goal["priority"].lower() == "must have":
            continue

        adjustable_goals.append(goal)

    if len(adjustable_goals) == 0:
        return None

    adjustable_goals.sort(
        key=lambda goal: (
            priority_order.get(goal["priority"].lower(), 99),
            -goal.get("periods_left", 0)
        )
    )

    return adjustable_goals[0]

In [ ]:
goal_to_adjust = find_adjustable_goal(goals)

if goal_to_adjust is None:
    print("No lower-priority goal is available for adjustment.")
else:
    print("Suggested goal to review:", goal_to_adjust["name"])
    print("Priority:", goal_to_adjust["priority"])
    print("Required per period:", goal_to_adjust["required_per_period"])

Suggested goal to review: Japan Trip
Priority: Important
Required per period: 85.0

In [ ]:
import math

def suggest_deadline_extension(goal, shortfall):
    """
    Suggest a longer deadline for a flexible goal
    so its required saving per period becomes lower.
    """

    if shortfall < 0:
        raise ValueError("Shortfall cannot be negative.")

    current_required = goal["required_per_period"]
    remaining_amount = goal["remaining_amount"]

    if current_required is None or current_required <= 0:
        return None

    # How much this goal would need to contribute
    # after covering the current shortfall
    new_required = current_required - shortfall

    if new_required <= 0:
        return None

    new_periods = math.ceil(
        remaining_amount / new_required
    )

    suggested_required = (
        remaining_amount / new_periods
    )

    return new_periods, suggested_required

In [ ]:
new_periods, new_required = suggest_deadline_extension(
    goal_to_adjust,
    updated_plan["shortfall"]
)

print("Current periods:", goal_to_adjust["periods_left"])
print("Suggested periods:", new_periods)
print("New required per period:", new_required)

Current periods: 20
Suggested periods: 58
New required per period: 29.310344827586206

In [ ]:
goals, released_money = edit_goal(
    goals,
    "Japan Trip",
    new_periods_left=new_periods
)

goals = update_goal_requirements(goals)

updated_plan = check_updated_plan(
    goals,
    352.69230769230774
)

print("Status:", updated_plan["status"])
print("Total required:", updated_plan["total_required"])
print("Surplus:", updated_plan["surplus"])
print("Shortfall:", updated_plan["shortfall"])

for goal in goals:
    if goal["status"] == "active":
        print(
            goal["name"],
            "- required:",
            goal["required_per_period"]
        )

Status: achievable
Total required: 352.4353448275862
Surplus: 0.2569628647215154
Shortfall: 0
Flight - required: 123.125
PC - required: 200.0
Japan Trip - required: 29.310344827586206

In [ ]:
for goal in goals:
    print(goal["name"], "-", goal["status"])

Flight - active
PC - active
Bag - completed
Japan Trip - active

In [ ]:
test_goals = [
    {
        "name": "Holiday",
        "target_amount": 2000,
        "current_saved": 500,
        "priority": "Nice to have",
        "periods_left": 20,
        "status": "active"
    }
]

test_goals, released_money = cancel_goal(
    test_goals,
    "Holiday"
)

print("Status:", test_goals[0]["status"])
print("Saved in goal:", test_goals[0]["current_saved"])
print("Released money:", released_money)

Status: cancelled
Saved in goal: 0
Released money: 500

In [ ]:
def find_expense_reduction_options(
    expenses,
    shortfall,
    budget_period="weekly"
):
    """
    Find optional flexible expenses that could be reduced
    to help cover a saving-plan shortfall.
    """

    if shortfall < 0:
        raise ValueError("Shortfall cannot be negative.")

    options = []

    for expense in expenses:

        if expense.get("status") != "confirmed":
            continue

        if expense.get("classification") != "optional flexible":
            continue

        user_amount = calculate_user_share(
            expense["amount"],
            expense.get("share_percent", 100)
        )

        normalised_amount = normalise_frequency(
            user_amount,
            expense["frequency"],
            budget_period
        )

        possible_reduction = min(
            normalised_amount,
            shortfall
        )

        suggested_amount = (
            normalised_amount - possible_reduction
        )

        options.append({
            "name": expense["name"],
            "current_amount": normalised_amount,
            "possible_reduction": possible_reduction,
            "suggested_amount": suggested_amount
        })

    # Review larger optional expenses first
    options.sort(
        key=lambda option: option["current_amount"],
        reverse=True
    )

    return options

In [ ]:
test_expenses = [
    {
        "name": "Rent",
        "amount": 520,
        "frequency": "weekly",
        "classification": "fixed",
        "status": "confirmed"
    },
    {
        "name": "Going out",
        "amount": 80,
        "frequency": "weekly",
        "classification": "optional flexible",
        "status": "confirmed"
    },
    {
        "name": "Streaming",
        "amount": 30,
        "frequency": "monthly",
        "classification": "optional flexible",
        "status": "confirmed"
    },
    {
        "name": "Groceries",
        "amount": 170,
        "frequency": "weekly",
        "classification": "essential flexible",
        "status": "confirmed"
    }
]

options = find_expense_reduction_options(
    test_expenses,
    32.93
)

for option in options:
    print(
        option["name"],
        "- current:",
        option["current_amount"],
        "- could reduce:",
        option["possible_reduction"],
        "- suggested:",
        option["suggested_amount"]
    )

Going out - current: 80.0 - could reduce: 32.93 - suggested: 47.07
Streaming - current: 6.923076923076923 - could reduce: 6.923076923076923 - suggested: 0.0

In [ ]:
def apply_expense_reduction(expenses, expense_name, reduction_amount, budget_period="weekly"):
    """
    Apply a confirmed reduction to an expense.

    reduction_amount is given in the current budgeting period.
    The function converts the change back to the expense's
    original frequency before updating it.
    """

    if reduction_amount < 0:
        raise ValueError("Reduction amount cannot be negative.")

    for expense in expenses:

        if expense["name"].lower() == expense_name.lower():

            if expense.get("status") != "confirmed":
                raise ValueError("Only confirmed expenses can be changed.")

            user_amount = calculate_user_share(
                expense["amount"],
                expense.get("share_percent", 100)
            )

            current_budget_amount = normalise_frequency(
                user_amount,
                expense["frequency"],
                budget_period
            )

            if reduction_amount > current_budget_amount:
                raise ValueError(
                    "Reduction cannot be greater than the current expense."
                )

            new_budget_amount = (
                current_budget_amount - reduction_amount
            )

            # Keep the original frequency correctly
            if current_budget_amount == 0:
                new_original_amount = 0
            else:
                remaining_ratio = (
                    new_budget_amount / current_budget_amount
                )

                new_original_amount = (
                    expense["amount"] * remaining_ratio
                )

            expense["amount"] = new_original_amount

            return expenses

    raise ValueError("Expense not found.")

In [ ]:
test_expenses = apply_expense_reduction(
    test_expenses,
    "Going out",
    30
)

for expense in test_expenses:
    if expense["name"] == "Going out":
        print("Original-frequency amount:", expense["amount"])
        print("Frequency:", expense["frequency"])

Original-frequency amount: 50.0
Frequency: weekly

In [ ]:
streaming_weekly = normalise_frequency(
    30,
    "monthly",
    "weekly"
)

test_expenses = apply_expense_reduction(
    test_expenses,
    "Streaming",
    streaming_weekly
)

for expense in test_expenses:
    if expense["name"] == "Streaming":
        print("Original-frequency amount:", expense["amount"])
        print("Frequency:", expense["frequency"])

Original-frequency amount: 0.0
Frequency: monthly

In [ ]:
new_total_expenses = calculate_total_expenses(
    test_expenses,
    budget_period="weekly"
)

new_money_remaining = calculate_money_remaining(
    1350,
    new_total_expenses
)

new_money_for_goals = calculate_money_for_goals(
    new_money_remaining,
    50
)

updated_plan = check_updated_plan(
    goals,
    new_money_for_goals
)

print("New total expenses:", new_total_expenses)
print("New money remaining:", new_money_remaining)
print("New money for goals:", new_money_for_goals)

print("Status:", updated_plan["status"])
print("Total required:", updated_plan["total_required"])
print("Surplus:", updated_plan["surplus"])
print("Shortfall:", updated_plan["shortfall"])

New total expenses: 740.0
New money remaining: 610.0
New money for goals: 560.0
Status: achievable
Total required: 352.4353448275862
Surplus: 207.56465517241378
Shortfall: 0

In [ ]:
import copy

plan_expenses = [
    {
        "name": "Rent",
        "amount": 520,
        "frequency": "weekly",
        "share_percent": 100,
        "classification": "fixed",
        "status": "confirmed"
    },
    {
        "name": "Groceries",
        "amount": 170,
        "frequency": "weekly",
        "share_percent": 100,
        "classification": "essential flexible",
        "status": "confirmed"
    },
    {
        "name": "Public transport",
        "amount": 45,
        "frequency": "weekly",
        "share_percent": 100,
        "classification": "essential flexible",
        "status": "confirmed"
    },
    {
        "name": "Phone",
        "amount": 60,
        "frequency": "monthly",
        "share_percent": 100,
        "classification": "fixed",
        "status": "confirmed"
    },
    {
        "name": "Electricity",
        "amount": 180,
        "frequency": "monthly",
        "share_percent": 100,
        "classification": "essential flexible",
        "status": "confirmed"
    },
    {
        "name": "Childcare",
        "amount": 100,  # after $120 restricted support
        "frequency": "weekly",
        "share_percent": 100,
        "classification": "fixed",
        "status": "confirmed"
    },
    {
        "name": "Streaming",
        "amount": 30,
        "frequency": "monthly",
        "share_percent": 100,
        "classification": "optional flexible",
        "status": "confirmed"
    },
    {
        "name": "Going out",
        "amount": 80,
        "frequency": "weekly",
        "share_percent": 100,
        "classification": "optional flexible",
        "status": "confirmed"
    }
]

In [ ]:
print(calculate_total_expenses(plan_expenses))

977.3076923076923

In [ ]:
adjusted_expenses = copy.deepcopy(plan_expenses)

adjusted_expenses = apply_expense_reduction(
    adjusted_expenses,
    "Going out",
    30
)

print(calculate_total_expenses(adjusted_expenses))

947.3076923076923

In [ ]:
plan_goals = [
    {
        "name": "Flight",
        "target_amount": 1500,
        "current_saved": 300,
        "priority": "Must have",
        "periods_left": 10,
        "status": "active"
    },
    {
        "name": "PC",
        "target_amount": 3500,
        "current_saved": 200,
        "priority": "Important",
        "periods_left": 16,
        "status": "active"
    },
    {
        "name": "Bag",
        "target_amount": 400,
        "current_saved": 0,
        "priority": "Nice to have",
        "periods_left": 16,
        "status": "active"
    }
]

plan_goals = update_goal_requirements(plan_goals)

In [ ]:
for goal in plan_goals:
    print(
        goal["name"],
        "- remaining:",
        goal["remaining_amount"],
        "- required:",
        goal["required_per_period"]
    )

Flight - remaining: 1200 - required: 120.0
PC - remaining: 3300 - required: 206.25
Bag - remaining: 400 - required: 25.0

In [ ]:
test_goals = copy.deepcopy(plan_goals)

In [ ]:
test_goals = add_goal(
    test_goals,
    "Japan Trip",
    2000,
    300,
    "Important",
    20
)

print("TEST GOALS:")
for goal in test_goals:
    print(goal["name"])

print("\nMAIN PLAN GOALS:")
for goal in plan_goals:
    print(goal["name"])

TEST GOALS:
Flight
PC
Bag
Japan Trip

MAIN PLAN GOALS:
Flight
PC
Bag

In [ ]:
def recalculate_full_plan(
    general_income,
    expenses,
    goals,
    buffer_amount=0,
    budget_period="weekly"
):
    """
    Recalculate the whole financial plan using the latest
    income, expenses, goals and safety buffer.

    The original expenses and goals are not changed.
    """

    goals_copy = copy.deepcopy(goals)

    total_expenses = calculate_total_expenses(
        expenses,
        budget_period
    )

    money_remaining = calculate_money_remaining(
        general_income,
        total_expenses
    )

    # If current expenses already exceed income,
    # there is no money available for saving goals.
    if money_remaining < 0:
        return {
            "status": "budget deficit",
            "total_expenses": total_expenses,
            "money_remaining": money_remaining,
            "money_for_goals": 0,
            "total_required": 0,
            "surplus": 0,
            "shortfall": abs(money_remaining),
            "goals": goals_copy
        }

    money_for_goals = calculate_money_for_goals(
        money_remaining,
        buffer_amount
    )

    goals_copy = update_goal_requirements(
        goals_copy
    )

    goal_result = check_updated_plan(
        goals_copy,
        money_for_goals
    )

    return {
        "status": goal_result["status"],
        "total_expenses": total_expenses,
        "money_remaining": money_remaining,
        "money_for_goals": money_for_goals,
        "total_required": goal_result["total_required"],
        "surplus": goal_result["surplus"],
        "shortfall": goal_result["shortfall"],
        "goals": goals_copy
    }

In [ ]:
baseline_result = recalculate_full_plan(
    general_income=1350,
    expenses=plan_expenses,
    goals=plan_goals,
    buffer_amount=50
)

print("Status:", baseline_result["status"])
print("Expenses:", baseline_result["total_expenses"])
print("Money remaining:", baseline_result["money_remaining"])
print("Money for goals:", baseline_result["money_for_goals"])
print("Goal requirement:", baseline_result["total_required"])
print("Shortfall:", baseline_result["shortfall"])

Status: not achievable
Expenses: 977.3076923076923
Money remaining: 372.69230769230774
Money for goals: 322.69230769230774
Goal requirement: 351.25
Shortfall: 28.557692307692264

## Step 5B – Gemini Integration

Gemini will be used to understand natural-language user input and support the conversation.

Gemini will not perform the main financial calculations. Financial calculations will continue to be handled by the Python functions created earlier.

In [ ]:
import requests
from google.colab import userdata

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")

GEMINI_MODEL = "gemini-3.5-flash-lite"

GEMINI_URL = (
    f"https://generativelanguage.googleapis.com/v1beta/"
    f"models/{GEMINI_MODEL}:generateContent"
)

print("Gemini API setup ready.")

Gemini API setup ready.

In [ ]:
import time
import requests

def ask_gemini(prompt):
    """
    Send a prompt to Gemini.
    Retry temporary API errors instead of crashing.
    """

    headers = {
        "x-goog-api-key": GEMINI_API_KEY,
        "Content-Type": "application/json"
    }

    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ]
    }

    for attempt in range(4):

        try:
            response = requests.post(
                GEMINI_URL,
                headers=headers,
                json=data,
                timeout=60
            )

            if response.status_code == 200:
                result = response.json()

                return (
                    result["candidates"][0]
                    ["content"]["parts"][0]["text"]
                )

            elif response.status_code in [408, 429, 500, 502, 503, 504]:

                wait_time = 2 ** attempt

                print(
                    f"Gemini temporarily unavailable. "
                    f"Retrying in {wait_time} seconds..."
                )

                time.sleep(wait_time)

            else:
                response.raise_for_status()

        except requests.exceptions.Timeout:

            wait_time = 2 ** attempt

            print(
                f"Gemini timed out. "
                f"Retrying in {wait_time} seconds..."
            )

            time.sleep(wait_time)

        except requests.exceptions.RequestException as error:
            return f"Gemini request failed: {error}"

    return "Gemini is temporarily unavailable. Please try again later."

In [ ]:
RUN_GEMINI_TEST = False

if RUN_GEMINI_TEST:
    reply = ask_gemini(
        "Reply with exactly: Gemini connection works."
    )
    print(reply)
else:
    print("Gemini connection test skipped.")

Gemini connection test skipped.

In [ ]:
import json
import time
import requests

def extract_expenses_with_gemini(user_text):
    """
    Extract expense information from natural language using Gemini.
    Handles temporary API errors and timeouts safely.
    """

    prompt = f"""
You are helping a personal budgeting application.

Extract all expenses clearly mentioned in the user's text.

Rules:
- Do not invent missing amounts.
- Do not invent missing frequencies.
- Do not invent sharing percentages.
- If information is unknown, use null.
- Keep the expense name simple.
- Frequency must be:
  weekly, fortnightly, monthly, yearly, irregular, or null.
- Classification must be:
  fixed, essential flexible, optional flexible, or null.
- Pattern must be:
  regular, variable, seasonal, temporary, one-off, irregular, or null.

Return JSON only.

User text:
{user_text}
"""

    headers = {
        "x-goog-api-key": GEMINI_API_KEY,
        "Content-Type": "application/json"
    }

    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json"
        }
    }

    for attempt in range(4):

        try:
            response = requests.post(
                GEMINI_URL,
                headers=headers,
                json=data,
                timeout=60
            )

            if response.status_code == 200:
                result = response.json()

                response_text = (
                    result["candidates"][0]
                    ["content"]["parts"][0]["text"]
                )

                return json.loads(response_text)

            elif response.status_code in [408, 429, 500, 502, 503, 504]:

                wait_time = 2 ** attempt

                print(
                    f"Gemini is temporarily unavailable. "
                    f"Retrying in {wait_time} seconds..."
                )

                time.sleep(wait_time)

            else:
                response.raise_for_status()

        except requests.exceptions.Timeout:

            wait_time = 2 ** attempt

            print(
                f"Gemini timed out. "
                f"Retrying in {wait_time} seconds..."
            )

            time.sleep(wait_time)

        except requests.exceptions.RequestException as error:
            print("Gemini request failed:", error)
            return None

    print(
        "Gemini is currently unavailable. "
        "Please try again later."
    )

    return None

In [ ]:
expense_text = """
I pay $520 rent every week, groceries are around $170 a week,
my phone is $60 a month, and I usually spend about $80 weekly
going out.
"""

extracted_data = extract_expenses_with_gemini(expense_text)

print(extracted_data)

[{'name': 'rent', 'amount': 520.0, 'frequency': 'weekly', 'classification': 'fixed', 'pattern': 'regular', 'sharing_percentage': None}, {'name': 'groceries', 'amount': 170.0, 'frequency': 'weekly', 'classification': 'essential flexible', 'pattern': 'variable', 'sharing_percentage': None}, {'name': 'phone', 'amount': 60.0, 'frequency': 'monthly', 'classification': 'fixed', 'pattern': 'regular', 'sharing_percentage': None}, {'name': 'going out', 'amount': 80.0, 'frequency': 'weekly', 'classification': 'optional flexible', 'pattern': 'variable', 'sharing_percentage': None}]

In [ ]:
import pandas as pd

expense_df = pd.DataFrame(extracted_data)

display(expense_df)

,name,amount,frequency,classification,pattern,sharing_percentage
0,rent,520.0,weekly,fixed,regular,None
1,groceries,170.0,weekly,essential flexible,variable,None
2,phone,60.0,monthly,fixed,regular,None
3,going out,80.0,weekly,optional flexible,variable,None

In [ ]:
def normalise_expense_name(name):
    """
    Convert similar expense names into one common name
    for missing-expense checking.
    """

    name = name.strip().lower()

    aliases = {
        "public transport": "transport",
        "bus": "transport",
        "train": "transport",
        "transportation": "transport",

        "mobile": "phone",
        "mobile phone": "phone",
        "phone bill": "phone",

        "food": "groceries",
        "grocery": "groceries",

        "eating out": "going out",
        "entertainment": "going out"
    }

    return aliases.get(name, name)


def find_missing_expenses(extracted_expenses, suggested_expenses):
    """
    Return suggested expenses that have not already
    been mentioned by the user.
    """

    existing_names = []

    for expense in extracted_expenses:
        existing_names.append(
            normalise_expense_name(expense["name"])
        )

    missing_expenses = []

    for expense_name in suggested_expenses:

        normalised_name = normalise_expense_name(
            expense_name
        )

        if normalised_name not in existing_names:
            missing_expenses.append(expense_name)

    return missing_expenses

In [ ]:
suggested_expenses = [
    "Rent",
    "Groceries",
    "Phone",
    "Going out",
    "Electricity",
    "Water",
    "Gas",
    "Internet",
    "Transport",
    "Insurance"
]

missing_expenses = find_missing_expenses(
    extracted_data,
    suggested_expenses
)

print("Possible missing expenses:")

for expense in missing_expenses:
    print("-", expense)

Possible missing expenses:
- Electricity
- Water
- Gas
- Internet
- Transport
- Insurance

In [ ]:
test_data = extracted_data + [
    {
        "name": "Public transport",
        "amount": 45,
        "frequency": "weekly",
        "classification": "essential flexible",
        "pattern": "regular"
    }
]

missing_expenses = find_missing_expenses(
    test_data,
    suggested_expenses
)

for expense in missing_expenses:
    print("-", expense)

- Electricity
- Water
- Gas
- Internet
- Insurance

In [ ]:
def build_expense_checklist(profile):
    """
    Build suggested expenses from the user's profile.
    Suggestions are cumulative.
    """

    suggestions = []

    def add_expense(name):
        if name not in suggestions:
            suggestions.append(name)

    # Common
    add_expense("Groceries")
    add_expense("Phone")
    add_expense("Transport")

    # Housing
    if profile.get("has_housing_cost", False):

        bills_status = profile.get("housing_bills", "unknown")

        if bills_status == "not_included":
            for bill in ["Electricity", "Water", "Gas", "Internet"]:
                add_expense(bill)

        elif bills_status == "partly_included":

            included_bills = profile.get("included_bills", [])

            for bill in ["Electricity", "Water", "Gas", "Internet"]:
                if bill not in included_bills:
                    add_expense(bill)

        elif bills_status == "unknown":
            add_expense("Housing bills")

    # Student
    if "student" in profile.get("roles", []):
        add_expense("Tuition")
        add_expense("Study materials")
        add_expense("Software")

    # Car
    if profile.get("has_car", False):
        add_expense("Fuel")
        add_expense("Car insurance")
        add_expense("Registration")
        add_expense("Servicing")

    # Children - cumulative by age group
    for child in profile.get("children", []):

        age_group = child.get("age_group")

        if age_group == "baby":
            add_expense("Nappies")
            add_expense("Baby food or formula")
            add_expense("Baby medical")
            add_expense("Childcare")

        elif age_group == "preschool":
            add_expense("Childcare")
            add_expense("Child clothing")
            add_expense("Child medical")

        elif age_group == "primary school":
            add_expense("School costs")
            add_expense("School activities")
            add_expense("Child clothing")
            add_expense("Child medical")

        elif age_group == "teen":
            add_expense("School costs")
            add_expense("Activities")
            add_expense("Child clothing")
            add_expense("Child transport")

        elif age_group == "university age":
            add_expense("Education support")
            add_expense("Transport support")

        elif age_group == "adult":
            if child.get("financially_supported", False):
                add_expense("Adult child support")

    # Pets
    for pet in profile.get("pets", []):

        add_expense("Pet food")
        add_expense("Vet")

        if pet.get("has_insurance", False):
            add_expense("Pet insurance")

        if pet.get("regular_medication", False):
            add_expense("Pet medication")

    # Other financially supported people
    for person in profile.get("dependants", []):

        responsibilities = person.get("responsibilities", [])

        if "financial support" in responsibilities:
            add_expense("Support payments")

        if "care responsibility" in responsibilities:
            add_expense("Care costs")

        if "medical support" in responsibilities:
            add_expense("Medical support")

    # Hobbies / interests
    if profile.get("has_hobbies", False):
        add_expense("Hobbies")

    return suggestions

In [ ]:
user_profile = {
    "roles": ["student"],
    "has_housing_cost": True,
    "has_car": False,
    "has_children": False,
    "has_pets": False,
    "supports_others": False
}

profile_checklist = build_expense_checklist(user_profile)

missing_expenses = find_missing_expenses(
    extracted_data,
    profile_checklist
)

print("Possible missing expenses:")

for expense in missing_expenses:
    print("-", expense)

Possible missing expenses:
- Transport
- Housing bills
- Tuition
- Study materials
- Software

In [ ]:
user_profile = {
    "roles": ["student"],
    "has_housing_cost": True,
    "housing_bills": "partly_included",
    "included_bills": ["Water", "Internet"],
    "has_car": False,
    "has_children": False,
    "has_pets": False,
    "supports_others": False
}

profile_checklist = build_expense_checklist(user_profile)

missing_expenses = find_missing_expenses(
    extracted_data,
    profile_checklist
)

for expense in missing_expenses:
    print("-", expense)

- Transport
- Electricity
- Gas
- Tuition
- Study materials
- Software

In [ ]:
complex_profile = {
    "roles": ["working"],
    "has_housing_cost": True,
    "housing_bills": "partly_included",
    "included_bills": ["Water"],
    "has_car": True,

    "children": [
        {"age_group": "baby"},
        {"age_group": "primary school"},
        {
            "age_group": "university age",
            "financially_supported": True
        }
    ],

    "pets": [
        {
            "type": "cat",
            "has_insurance": False,
            "regular_medication": False
        },
        {
            "type": "dog",
            "has_insurance": True,
            "regular_medication": True
        }
    ],

    "dependants": [
        {
            "relationship": "parent",
            "responsibilities": [
                "financial support",
                "medical support"
            ]
        }
    ],

    "has_hobbies": True
}

profile_checklist = build_expense_checklist(complex_profile)

for expense in profile_checklist:
    print("-", expense)

- Groceries
- Phone
- Transport
- Electricity
- Gas
- Internet
- Fuel
- Car insurance
- Registration
- Servicing
- Nappies
- Baby food or formula
- Baby medical
- Childcare
- School costs
- School activities
- Child clothing
- Child medical
- Education support
- Transport support
- Pet food
- Vet
- Pet insurance
- Pet medication
- Support payments
- Medical support
- Hobbies

In [ ]:
def get_expense_followups(profile, extracted_expenses):
    """
    Build the profile-based checklist and return only
    expenses that the user has not already mentioned.
    """

    checklist = build_expense_checklist(profile)

    missing_expenses = find_missing_expenses(
        extracted_expenses,
        checklist
    )

    return missing_expenses

In [ ]:
followup_expenses = get_expense_followups(
    complex_profile,
    extracted_data
)

print("Expenses to ask the user about:")

for expense in followup_expenses:
    print("-", expense)

Expenses to ask the user about:
- Transport
- Electricity
- Gas
- Internet
- Fuel
- Car insurance
- Registration
- Servicing
- Nappies
- Baby food or formula
- Baby medical
- Childcare
- School costs
- School activities
- Child clothing
- Child medical
- Education support
- Transport support
- Pet food
- Vet
- Pet insurance
- Pet medication
- Support payments
- Medical support
- Hobbies

In [ ]:
def create_followup_survey(missing_expenses):
    """
    Create survey records for possible missing expenses.
    """

    survey = []

    for expense_name in missing_expenses:
        survey.append({
            "name": expense_name,
            "status": "unanswered",
            "amount": None,
            "frequency": None
        })

    return survey

In [ ]:
expense_survey = create_followup_survey(
    followup_expenses
)

for item in expense_survey[:5]:
    print(item)

{'name': 'Transport', 'status': 'unanswered', 'amount': None, 'frequency': None}
{'name': 'Electricity', 'status': 'unanswered', 'amount': None, 'frequency': None}
{'name': 'Gas', 'status': 'unanswered', 'amount': None, 'frequency': None}
{'name': 'Internet', 'status': 'unanswered', 'amount': None, 'frequency': None}
{'name': 'Fuel', 'status': 'unanswered', 'amount': None, 'frequency': None}

In [ ]:
def answer_expense_survey(
    survey,
    expense_name,
    status,
    amount=None,
    frequency=None
):
    """
    Record the user's answer for one possible missing expense.
    """

    valid_statuses = [
        "yes",
        "not applicable",
        "included",
        "paid by someone else",
        "not sure"
    ]

    if status.lower() not in valid_statuses:
        raise ValueError("Invalid survey status.")

    for item in survey:

        if item["name"].lower() == expense_name.lower():

            item["status"] = status.lower()

            if status.lower() == "yes":

                if amount is None or frequency is None:
                    raise ValueError(
                        "Amount and frequency are required."
                    )

                if amount < 0:
                    raise ValueError(
                        "Amount cannot be negative."
                    )

                item["amount"] = amount
                item["frequency"] = frequency

            else:
                item["amount"] = None
                item["frequency"] = None

            return survey

    raise ValueError("Expense not found in survey.")

In [ ]:
expense_survey = answer_expense_survey(
    expense_survey,
    "Transport",
    "yes",
    45,
    "weekly"
)

expense_survey = answer_expense_survey(
    expense_survey,
    "Electricity",
    "included"
)

expense_survey = answer_expense_survey(
    expense_survey,
    "Gas",
    "not applicable"
)

for item in expense_survey[:5]:
    print(item)

{'name': 'Transport', 'status': 'yes', 'amount': 45, 'frequency': 'weekly'}
{'name': 'Electricity', 'status': 'included', 'amount': None, 'frequency': None}
{'name': 'Gas', 'status': 'not applicable', 'amount': None, 'frequency': None}
{'name': 'Internet', 'status': 'unanswered', 'amount': None, 'frequency': None}
{'name': 'Fuel', 'status': 'unanswered', 'amount': None, 'frequency': None}

In [ ]:
def merge_survey_expenses(extracted_expenses, survey):
    """
    Add confirmed survey expenses into the main expense list.

    Only items marked 'yes' are added.
    """

    updated_expenses = extracted_expenses.copy()

    for item in survey:

        if item["status"] == "yes":

            new_expense = {
                "name": item["name"],
                "amount": item["amount"],
                "frequency": item["frequency"],
                "classification": None,
                "pattern": None
            }

            updated_expenses.append(new_expense)

    return updated_expenses

In [ ]:
final_expenses = merge_survey_expenses(
    extracted_data,
    expense_survey
)

expense_df = pd.DataFrame(final_expenses)

display(expense_df)

,name,amount,frequency,classification,pattern,sharing_percentage
0,rent,520.0,weekly,fixed,regular,NaN
1,groceries,170.0,weekly,essential flexible,variable,NaN
2,phone,60.0,monthly,fixed,regular,NaN
3,going out,80.0,weekly,optional flexible,variable,NaN
4,Transport,45.0,weekly,None,None,NaN

In [ ]:
def clean_expense_data(expenses):
    """
    Make expense records use one consistent structure.
    """

    cleaned_expenses = []

    for expense in expenses:

        cleaned = expense.copy()

        # Keep one consistent name for sharing percentage
        if "sharing_percentage" in cleaned:
            cleaned["share_percent"] = cleaned.pop(
                "sharing_percentage"
            )

        if cleaned.get("share_percent") is None:
            cleaned["share_percent"] = 100

        # Default status for confirmed expenses
        cleaned["status"] = cleaned.get(
            "status",
            "confirmed"
        )

        # Simple defaults for common expenses
        if cleaned["name"].lower() == "transport":

            if cleaned.get("classification") is None:
                cleaned["classification"] = "essential flexible"

            if cleaned.get("pattern") is None:
                cleaned["pattern"] = "variable"

        cleaned_expenses.append(cleaned)

    return cleaned_expenses

In [ ]:
final_expenses = clean_expense_data(
    final_expenses
)

expense_df = pd.DataFrame(final_expenses)

display(expense_df)

,name,amount,frequency,classification,pattern,share_percent,status
0,rent,520.0,weekly,fixed,regular,100,confirmed
1,groceries,170.0,weekly,essential flexible,variable,100,confirmed
2,phone,60.0,monthly,fixed,regular,100,confirmed
3,going out,80.0,weekly,optional flexible,variable,100,confirmed
4,Transport,45.0,weekly,essential flexible,variable,100,confirmed

In [ ]:
user_total_expenses = calculate_total_expenses(
    final_expenses,
    budget_period="weekly"
)

print("Total weekly expenses:", user_total_expenses)

Total weekly expenses: 828.8461538461538

In [ ]:
def extract_income_with_gemini(user_text):
    """
    Extract income sources from natural language.
    """

    prompt = f"""
You are helping a personal budgeting application.

Extract only income clearly mentioned by the user.

Important rules:

1. "amount" means the TOTAL income received from that source.
2. If the user says only part of an income is available to the budget:
   - keep the full income in "amount"
   - use availability_type = "fixed" or "percent"
   - put the usable amount or percentage in availability_value

Example:
"My partner earns $900 weekly but contributes $350 to the household."
means:
amount = 900
availability_type = "fixed"
availability_value = 350
restricted = false

3. restricted = true ONLY when the income must be used for a specific purpose,
for example:
- childcare payment only for childcare
- education grant only for study costs

A partner contribution is NOT restricted income.

4. Do not guess missing amounts or frequencies.

5. frequency must be:
weekly, fortnightly, monthly, yearly, irregular, or null.

6. availability_type must be:
all, fixed, percent, none, or null.

Return JSON only in this structure:

{{
  "income": [
    {{
      "name": "income source",
      "amount": 0,
      "frequency": "weekly",
      "availability_type": "all",
      "availability_value": null,
      "restricted": false
    }}
  ]
}}

User text:
{user_text}
"""

    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json"
        }
    }

    for attempt in range(4):

        try:
            response = requests.post(
                GEMINI_URL,
                headers={
                    "x-goog-api-key": GEMINI_API_KEY,
                    "Content-Type": "application/json"
                },
                json=data,
                timeout=60
            )

            if response.status_code == 200:
                result = response.json()

                text = (
                    result["candidates"][0]
                    ["content"]["parts"][0]["text"]
                )

                return json.loads(text)["income"]

            if response.status_code in [408, 429, 500, 502, 503, 504]:
                wait_time = 2 ** attempt
                print(f"Retrying in {wait_time} seconds...")
                time.sleep(wait_time)
                continue

            response.raise_for_status()

        except requests.exceptions.Timeout:
            wait_time = 2 ** attempt
            print(f"Gemini timed out. Retrying in {wait_time} seconds...")
            time.sleep(wait_time)

    return None

In [ ]:
income_text = """
I earn about $1000 a week from work.
My partner earns $900 weekly but only contributes $350
to our household each week.
"""

income_data = extract_income_with_gemini(income_text)

print(income_data)

[{'name': 'work', 'amount': 1000, 'frequency': 'weekly', 'availability_type': 'all', 'availability_value': None, 'restricted': False}, {'name': 'partner', 'amount': 900, 'frequency': 'weekly', 'availability_type': 'fixed', 'availability_value': 350, 'restricted': False}]

In [ ]:
general_income, restricted_income = calculate_income_totals(
    income_data,
    budget_period="weekly"
)

print("General income available:", general_income)
print("Restricted income:", restricted_income)

General income available: 1350.0
Restricted income: 0

In [ ]:
money_remaining = calculate_money_remaining(
    general_income,
    user_total_expenses
)

print("Money remaining after expenses:", money_remaining)

Money remaining after expenses: 521.1538461538462

In [ ]:
suggested_buffer = calculate_suggested_buffer(
    general_income
)

money_for_goals = calculate_money_for_goals(
    money_remaining,
    suggested_buffer
)

print("Suggested safety buffer:", suggested_buffer)
print("Money available for goals:", money_for_goals)

Suggested safety buffer: 67.5
Money available for goals: 453.6538461538462

In [ ]:
def extract_goals_with_gemini(user_text):
    """
    Extract saving goals from natural language.
    Gemini only extracts information.
    Python will do the calculations later.
    """

    prompt = f"""
You are helping a personal budgeting application.

Extract all saving goals clearly mentioned by the user.

Rules:
- Do not invent missing amounts.
- Do not invent deadlines.
- Do not calculate saving requirements.
- Keep the user's deadline wording in deadline_text.
- current_saved is null if the user does not mention existing savings.
- priority must be:
  must have, important, nice to have, or null.
- currency should use a currency code such as AUD, USD, VND.
- If currency is not stated, use AUD.
- Return JSON only.

Format:

{{
  "goals": [
    {{
      "name": "goal name",
      "target_amount": 0,
      "currency": "AUD",
      "deadline_text": "February",
      "priority": "important",
      "current_saved": null
    }}
  ]
}}

User text:
{user_text}
"""

    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json"
        }
    }

    for attempt in range(4):

        try:
            response = requests.post(
                GEMINI_URL,
                headers={
                    "x-goog-api-key": GEMINI_API_KEY,
                    "Content-Type": "application/json"
                },
                json=data,
                timeout=60
            )

            if response.status_code == 200:
                result = response.json()

                text = (
                    result["candidates"][0]
                    ["content"]["parts"][0]["text"]
                )

                return json.loads(text)["goals"]

            if response.status_code in [408, 429, 500, 502, 503, 504]:
                wait_time = 2 ** attempt
                print(f"Retrying in {wait_time} seconds...")
                time.sleep(wait_time)
                continue

            response.raise_for_status()

        except requests.exceptions.Timeout:
            wait_time = 2 ** attempt
            print(
                f"Gemini timed out. Retrying in "
                f"{wait_time} seconds..."
            )
            time.sleep(wait_time)

    return None

In [ ]:
goal_text = """
I want to save $1500 for a flight by December,
$3500 for a new PC by July,
and $400 for a bag by February.

The flight is a must have,
the PC is important,
and the bag is nice to have.
"""

goal_data = extract_goals_with_gemini(goal_text)

print(goal_data)

Retrying in 1 seconds...
[{'name': 'flight', 'target_amount': 1500, 'currency': 'AUD', 'deadline_text': 'December', 'priority': 'must have', 'current_saved': None}, {'name': 'new PC', 'target_amount': 3500, 'currency': 'AUD', 'deadline_text': 'July', 'priority': 'important', 'current_saved': None}, {'name': 'bag', 'target_amount': 400, 'currency': 'AUD', 'deadline_text': 'February', 'priority': 'nice to have', 'current_saved': None}]

In [ ]:
def find_goal_followups(goals):
    """
    Find missing or unclear information before
    calculating a saving plan.
    """

    followups = []

    month_names = [
        "january", "february", "march", "april",
        "may", "june", "july", "august",
        "september", "october", "november", "december"
    ]

    for goal in goals:

        missing = []

        if goal.get("target_amount") is None:
            missing.append("target amount")

        if goal.get("current_saved") is None:
            missing.append("current savings")

        if goal.get("priority") is None:
            missing.append("priority")

        deadline = goal.get("deadline_text")

        if deadline is None:
            missing.append("deadline")

        elif deadline.strip().lower() in month_names:
            missing.append("exact deadline date")

        if missing:
            followups.append({
                "name": goal["name"],
                "missing": missing
            })

    return followups

In [ ]:
goal_followups = find_goal_followups(goal_data)

for item in goal_followups:
    print(item["name"], "->", item["missing"])

flight -> ['current savings', 'exact deadline date']
new PC -> ['current savings', 'exact deadline date']
bag -> ['current savings', 'exact deadline date']

In [ ]:
def update_goal_details(
    goals,
    goal_name,
    current_saved=None,
    deadline=None
):
    """
    Update missing goal information supplied by the user.
    """

    for goal in goals:

        if goal["name"].lower() == goal_name.lower():

            if current_saved is not None:

                if current_saved < 0:
                    raise ValueError(
                        "Current savings cannot be negative."
                    )

                goal["current_saved"] = current_saved

            if deadline is not None:
                goal["deadline"] = deadline

            return goals

    raise ValueError("Goal not found.")

In [ ]:
goal_data = update_goal_details(
    goal_data,
    "flight",
    current_saved=300,
    deadline="2026-12-20"
)

goal_data = update_goal_details(
    goal_data,
    "new PC",
    current_saved=200,
    deadline="2027-07-01"
)

goal_data = update_goal_details(
    goal_data,
    "bag",
    current_saved=0,
    deadline="2027-02-01"
)

for goal in goal_data:
    print(
        goal["name"],
        "- saved:",
        goal["current_saved"],
        "- deadline:",
        goal["deadline"]
    )

flight - saved: 300 - deadline: 2026-12-20
new PC - saved: 200 - deadline: 2027-07-01
bag - saved: 0 - deadline: 2027-02-01

In [ ]:
from datetime import datetime, date
import math

def calculate_weeks_left(deadline, start_date=None):
    """
    Calculate how many weekly saving periods remain
    until the goal deadline.
    """

    if start_date is None:
        start_date = date.today()

    deadline_date = datetime.strptime(
        deadline,
        "%Y-%m-%d"
    ).date()

    days_left = (deadline_date - start_date).days

    if days_left < 0:
        return 0

    return math.ceil(days_left / 7)

In [ ]:
for goal in goal_data:

    goal["periods_left"] = calculate_weeks_left(
        goal["deadline"]
    )

    print(
        goal["name"],
        "- periods left:",
        goal["periods_left"]
    )

flight - periods left: 10
new PC - periods left: 37
bag - periods left: 16

In [ ]:
def clean_goal_data(goals):
    """
    Prepare extracted goals for the calculation engine.
    """

    cleaned_goals = []

    for goal in goals:

        cleaned = goal.copy()

        if cleaned.get("current_saved") is None:
            cleaned["current_saved"] = 0

        cleaned["status"] = cleaned.get(
            "status",
            "active"
        )

        cleaned_goals.append(cleaned)

    return cleaned_goals

In [ ]:
final_goals = clean_goal_data(goal_data)

final_goals = update_goal_requirements(
    final_goals
)

for goal in final_goals:
    print(
        goal["name"],
        "- remaining:",
        goal["remaining_amount"],
        "- required per week:",
        goal["required_per_period"],
        "- status:",
        goal["status"]
    )

flight - remaining: 1200 - required per week: 120.0 - status: active
new PC - remaining: 3300 - required per week: 89.1891891891892 - status: active
bag - remaining: 400 - required per week: 25.0 - status: active

In [ ]:
plan_result = check_updated_plan(
    final_goals,
    money_for_goals
)

print("Status:", plan_result["status"])
print("Total required per week:", plan_result["total_required"])
print("Surplus:", plan_result["surplus"])
print("Shortfall:", plan_result["shortfall"])

Status: achievable
Total required per week: 234.1891891891892
Surplus: 219.464656964657
Shortfall: 0

In [ ]:
allocation_result = allocate_goal_savings(
    final_goals,
    money_for_goals
)

print("Status:", allocation_result["status"])
print("Allocations:", allocation_result["allocations"])
print("Extra money:", allocation_result["extra_money"])
print("Shortfall:", allocation_result["shortfall"])

Status: achievable
Allocations: {'flight': 120.0, 'new PC': 89.1891891891892, 'bag': 25.0}
Extra money: 219.464656964657
Shortfall: 0

In [ ]:
def use_extra_money_for_priority(
    goals,
    allocations,
    extra_money
):
    """
    Add extra money to active goals by priority
    without saving more than each goal still needs.
    """

    updated_allocations = allocations.copy()

    priority_order = {
        "must have": 1,
        "important": 2,
        "nice to have": 3
    }

    active_goals = [
        goal for goal in goals
        if goal["status"] == "active"
    ]

    active_goals.sort(
        key=lambda goal: priority_order.get(
            goal["priority"].lower(),
            99
        )
    )

    money_left = extra_money

    for goal in active_goals:

        if money_left <= 0:
            break

        current_allocation = updated_allocations.get(
            goal["name"],
            0
        )

        remaining_after_base = max(
            goal["remaining_amount"] - current_allocation,
            0
        )

        extra_for_goal = min(
            money_left,
            remaining_after_base
        )

        updated_allocations[goal["name"]] = (
            current_allocation + extra_for_goal
        )

        money_left -= extra_for_goal

    return updated_allocations, money_left

In [ ]:
priority_allocations, money_left = (
    use_extra_money_for_priority(
        final_goals,
        allocation_result["allocations"],
        allocation_result["extra_money"]
    )
)

print("Priority allocations:", priority_allocations)
print("Money still unallocated:", money_left)

Priority allocations: {'flight': 339.464656964657, 'new PC': 89.1891891891892, 'bag': 25.0}
Money still unallocated: 0.0

In [ ]:
weekly_goals = copy.deepcopy(final_goals)

weekly_goals, messages, unused_money = apply_goal_allocations(
    weekly_goals,
    priority_allocations
)

for goal in weekly_goals:
    print(
        goal["name"],
        "- saved:",
        goal["current_saved"],
        "- status:",
        goal["status"]
    )

print("Unused money:", unused_money)

for message in messages:
    print(message)

flight - saved: 639.464656964657 - status: active
new PC - saved: 289.18918918918916 - status: active
bag - saved: 25.0 - status: active
Unused money: 0.0
flight still needs $860.54.
new PC still needs $3210.81.
bag still needs $375.00.

In [ ]:
import json
import os

STATE_FILE = "/content/finance_app_state.json"


def save_app_state(state):
    """
    Save the current finance app state to a JSON file.
    """

    with open(STATE_FILE, "w") as file:
        json.dump(state, file, indent=4)

    return STATE_FILE


def load_app_state(file_path=STATE_FILE):
    """
    Load previously saved finance app state.
    """

    if not os.path.exists(file_path):
        return None

    with open(file_path, "r") as file:
        return json.load(file)

## Step 5C – Spending Tracking

The application will allow the user to record actual spending and compare it with the planned budget. This helps the user see where they overspent or underspent and how this may affect their saving goals.

In [ ]:
def add_transaction(
    transactions,
    date,
    category,
    amount,
    description=""
):
    """
    Add one actual spending transaction.
    """

    if amount < 0:
        raise ValueError("Transaction amount cannot be negative.")

    transaction = {
        "date": date,
        "category": category,
        "amount": amount,
        "description": description
    }

    transactions.append(transaction)

    return transactions

In [ ]:
transactions = []

transactions = add_transaction(
    transactions,
    "2026-10-14",
    "Groceries",
    45,
    "Weekly supermarket shop"
)

transactions = add_transaction(
    transactions,
    "2026-10-14",
    "Going out",
    30,
    "Dinner"
)

print(transactions)

[{'date': '2026-10-14', 'category': 'Groceries', 'amount': 45, 'description': 'Weekly supermarket shop'}, {'date': '2026-10-14', 'category': 'Going out', 'amount': 30, 'description': 'Dinner'}]

In [ ]:
def compare_actual_to_plan(
    transactions,
    planned_expenses,
    budget_period="weekly"
):
    """
    Compare logged spending with the planned budget
    for each category that has transactions.
    """

    actual_totals = {}

    # Add actual spending by category
    for transaction in transactions:

        category = normalise_expense_name(
            transaction["category"]
        )

        actual_totals[category] = (
            actual_totals.get(category, 0)
            + transaction["amount"]
        )

    planned_totals = {}

    # Build planned spending amounts
    for expense in planned_expenses:

        if expense.get("status") != "confirmed":
            continue

        category = normalise_expense_name(
            expense["name"]
        )

        user_amount = calculate_user_share(
            expense["amount"],
            expense.get("share_percent", 100)
        )

        planned_amount = normalise_frequency(
            user_amount,
            expense["frequency"],
            budget_period
        )

        planned_totals[category] = (
            planned_totals.get(category, 0)
            + planned_amount
        )

    comparison = []

    for category, actual in actual_totals.items():

        planned = planned_totals.get(category)

        if planned is None:
            difference = None
            status = "unplanned expense"

        else:
            difference = actual - planned

            if difference > 0:
                status = "over budget"

            elif difference < 0:
                status = "under budget"

            else:
                status = "on budget"

        comparison.append({
            "category": category.title(),
            "planned": planned,
            "actual": actual,
            "difference": difference,
            "status": status
        })

    return comparison

In [ ]:
spending_comparison = compare_actual_to_plan(
    transactions,
    final_expenses
)

comparison_df = pd.DataFrame(
    spending_comparison
)

display(comparison_df)

    category  planned  actual  difference        status
0  Groceries    170.0      45      -125.0  under budget
1  Going Out     80.0      30       -50.0  under budget

In [ ]:
from datetime import datetime, timedelta, date

def filter_transactions_by_week(
    transactions,
    reference_date=None
):
    """
    Return transactions from the Monday-Sunday week
    containing the reference date.
    """

    if reference_date is None:
        reference_date = date.today()

    if isinstance(reference_date, str):
        reference_date = datetime.strptime(
            reference_date,
            "%Y-%m-%d"
        ).date()

    week_start = reference_date - timedelta(
        days=reference_date.weekday()
    )

    week_end = week_start + timedelta(days=6)

    weekly_transactions = []

    for transaction in transactions:

        transaction_date = datetime.strptime(
            transaction["date"],
            "%Y-%m-%d"
        ).date()

        if week_start <= transaction_date <= week_end:
            weekly_transactions.append(transaction)

    return weekly_transactions

In [ ]:
weekly_transactions = filter_transactions_by_week(
    transactions,
    "2026-10-14"
)

print(weekly_transactions)

[{'date': '2026-10-14', 'category': 'Groceries', 'amount': 45, 'description': 'Weekly supermarket shop'}, {'date': '2026-10-14', 'category': 'Going out', 'amount': 30, 'description': 'Dinner'}]

In [ ]:
spending_comparison = compare_actual_to_plan(
    weekly_transactions,
    final_expenses
)

comparison_df = pd.DataFrame(spending_comparison)

display(comparison_df)

    category  planned  actual  difference        status
0  Groceries    170.0      45      -125.0  under budget
1  Going Out     80.0      30       -50.0  under budget

In [ ]:
test_transactions = copy.deepcopy(transactions)

test_transactions = add_transaction(
    test_transactions,
    "2026-10-15",
    "Groceries",
    140,
    "Extra grocery shopping"
)

test_transactions = add_transaction(
    test_transactions,
    "2026-10-16",
    "Going out",
    60,
    "Night out"
)

test_week = filter_transactions_by_week(
    test_transactions,
    "2026-10-14"
)

test_comparison = compare_actual_to_plan(
    test_week,
    final_expenses
)

display(pd.DataFrame(test_comparison))

    category  planned  actual  difference       status
0  Groceries    170.0     185        15.0  over budget
1  Going Out     80.0      90        10.0  over budget

In [ ]:
def compare_actual_to_plan(
    transactions,
    planned_expenses,
    budget_period="weekly",
    period_complete=False
):
    """
    Compare actual spending with the planned budget.
    """

    actual_totals = {}

    for transaction in transactions:

        category = normalise_expense_name(
            transaction["category"]
        )

        actual_totals[category] = (
            actual_totals.get(category, 0)
            + transaction["amount"]
        )

    planned_totals = {}

    for expense in planned_expenses:

        if expense.get("status") != "confirmed":
            continue

        category = normalise_expense_name(
            expense["name"]
        )

        user_amount = calculate_user_share(
            expense["amount"],
            expense.get("share_percent", 100)
        )

        planned_amount = normalise_frequency(
            user_amount,
            expense["frequency"],
            budget_period
        )

        planned_totals[category] = (
            planned_totals.get(category, 0)
            + planned_amount
        )

    comparison = []

    for category, actual in actual_totals.items():

        planned = planned_totals.get(category)

        if planned is None:
            difference = None
            status = "unplanned expense"

        else:
            difference = actual - planned

            if difference > 0:
                status = "over budget"

            elif difference < 0:
                if period_complete:
                    status = "under budget"
                else:
                    status = "within budget so far"

            else:
                status = "on budget"

        comparison.append({
            "category": category.title(),
            "planned": planned,
            "actual": actual,
            "difference": difference,
            "status": status
        })

    return comparison

In [ ]:
def calculate_overspending_impact(
    spending_comparison,
    normal_money_for_goals,
    goals
):
    """
    Reduce this week's goal money by actual overspending
    and check whether the goal plan is still achievable.
    """

    total_overspending = 0

    for item in spending_comparison:

        if (
            item["difference"] is not None
            and item["difference"] > 0
        ):
            total_overspending += item["difference"]

    adjusted_money_for_goals = max(
        normal_money_for_goals - total_overspending,
        0
    )

    updated_plan = check_updated_plan(
        goals,
        adjusted_money_for_goals
    )

    return {
        "total_overspending": total_overspending,
        "money_for_goals_after_overspending":
            adjusted_money_for_goals,
        "status": updated_plan["status"],
        "surplus": updated_plan["surplus"],
        "shortfall": updated_plan["shortfall"]
    }

In [ ]:
impact = calculate_overspending_impact(
    test_comparison,
    money_for_goals,
    final_goals
)

print("Total overspending:", impact["total_overspending"])
print(
    "Money for goals after overspending:",
    impact["money_for_goals_after_overspending"]
)
print("Goal plan status:", impact["status"])
print("Surplus:", impact["surplus"])
print("Shortfall:", impact["shortfall"])

Total overspending: 25.0
Money for goals after overspending: 428.6538461538462
Goal plan status: achievable
Surplus: 194.464656964657
Shortfall: 0

In [ ]:
def create_weekly_feedback(
    spending_comparison,
    impact
):
    """
    Create a simple weekly tracking summary
    from calculated financial results.
    """

    messages = []

    for item in spending_comparison:

        if item["status"] == "over budget":
            messages.append(
                f"{item['category']} was over budget "
                f"by ${item['difference']:.2f}."
            )

    if impact["total_overspending"] > 0:
        messages.append(
            f"Total overspending this week was "
            f"${impact['total_overspending']:.2f}."
        )

    if impact["status"] == "achievable":
        messages.append(
            "Your current saving goals are still achievable."
        )

    else:
        messages.append(
            f"Your saving plan is short by "
            f"${impact['shortfall']:.2f} this week."
        )

    return messages

In [ ]:
weekly_feedback = create_weekly_feedback(
    test_comparison,
    impact
)

for message in weekly_feedback:
    print(message)

Groceries was over budget by $15.00.
Going Out was over budget by $10.00.
Total overspending this week was $25.00.
Your current saving goals are still achievable.

In [ ]:
def generate_weekly_advice(feedback_messages):
    """
    Ask Gemini to rewrite verified Python results
    into a short, friendly finance summary.
    """

    facts = "\n".join(feedback_messages)

    prompt = f"""
You are a supportive personal budgeting assistant.

Rewrite the verified facts below into a short and clear weekly summary.

Rules:
- Do not change any numbers.
- Do not strengthen or weaken the verified conclusions.
- If the facts say "achievable", say "achievable", not "completely", "definitely", or "guaranteed".
- Do not invent new financial information.
- Do not claim something is wrong unless the facts say so.
- Keep the response concise and practical.
- Use a friendly but professional tone.

Verified facts:
{facts}
"""

    response = ask_gemini(prompt)

    # Fallback if Gemini is unavailable
    if (
        response is None
        or "temporarily unavailable" in response.lower()
        or "request failed" in response.lower()
    ):
        return "\n".join(feedback_messages)

    return response

In [ ]:
weekly_advice = generate_weekly_advice(
    weekly_feedback
)

print(weekly_advice)

Gemini temporarily unavailable. Retrying in 1 seconds...
Here is your weekly financial summary:

This week, Groceries went over budget by $15.00 and Going Out was over budget by $10.00, bringing your total overspending to $25.00.

The good news is that your current saving goals are still achievable. Let's keep up the good work next week!

In [ ]:
def load_transactions_csv(file_path):
    """
    Load transaction history from a CSV file.
    """

    df = pd.read_csv(file_path)

    required_columns = [
        "Date",
        "Category",
        "Amount",
        "Description"
    ]

    for column in required_columns:
        if column not in df.columns:
            raise ValueError(
                f"Missing required column: {column}"
            )

    df["Amount"] = pd.to_numeric(
        df["Amount"],
        errors="coerce"
    )

    df = df.dropna(subset=["Amount"])

    transactions = []

    for _, row in df.iterrows():
        transactions.append({
            "date": str(row["Date"]),
            "category": str(row["Category"]),
            "amount": float(row["Amount"]),
            "description": str(row["Description"])
        })

    return transactions

In [ ]:
sample_transactions = pd.DataFrame({
    "Date": [
        "2026-10-12",
        "2026-10-13",
        "2026-10-14",
        "2026-10-15"
    ],
    "Category": [
        "Groceries",
        "Going out",
        "Transport",
        "Groceries"
    ],
    "Amount": [
        60,
        25,
        20,
        95
    ],
    "Description": [
        "Supermarket",
        "Coffee and dinner",
        "Bus and train",
        "Extra groceries"
    ]
})

sample_csv_path = "/content/sample_transactions.csv"

sample_transactions.to_csv(
    sample_csv_path,
    index=False
)

print("Sample CSV created.")

Sample CSV created.

In [ ]:
csv_transactions = load_transactions_csv(
    sample_csv_path
)

csv_df = pd.DataFrame(csv_transactions)

display(csv_df)

         date   category  amount        description
0  2026-10-12  Groceries    60.0        Supermarket
1  2026-10-13  Going out    25.0  Coffee and dinner
2  2026-10-14  Transport    20.0      Bus and train
3  2026-10-15  Groceries    95.0    Extra groceries

In [ ]:
import json

STATE_FILE = "/content/finance_app_state.json"


def save_app_state(state, file_path=STATE_FILE):
    """
    Save the user's finance data to a JSON file.
    """

    with open(file_path, "w") as file:
        json.dump(state, file, indent=4)

    return file_path


def load_app_state(file_path=STATE_FILE):
    """
    Load previously saved finance data.
    """

    with open(file_path, "r") as file:
        return json.load(file)

In [ ]:
app_state = {
    "income": income_data,
    "expenses": final_expenses,
    "goals": final_goals,
    "buffer": suggested_buffer,
    "transactions": csv_transactions
}

saved_file = save_app_state(app_state)

print("Saved to:", saved_file)

Saved to: /content/finance_app_state.json

In [ ]:
loaded_state = load_app_state()

print("Income sources:", len(loaded_state["income"]))
print("Expenses:", len(loaded_state["expenses"]))
print("Goals:", len(loaded_state["goals"]))
print("Transactions:", len(loaded_state["transactions"]))
print("Buffer:", loaded_state["buffer"])

Income sources: 2
Expenses: 5
Goals: 3
Transactions: 4
Buffer: 67.5

In [ ]:
def replan_from_state(state, reference_date=None):
    """
    Recalculate the full saving plan from the latest saved state.
    """

    state_copy = copy.deepcopy(state)

    # 1. Recalculate usable income
    general_income, restricted_income = calculate_income_totals(
        state_copy["income"],
        budget_period="weekly"
    )

    # 2. Recalculate weekly expenses
    total_expenses = calculate_total_expenses(
        state_copy["expenses"],
        budget_period="weekly"
    )

    # 3. Money remaining after expenses
    money_remaining = calculate_money_remaining(
        general_income,
        total_expenses
    )

    buffer_amount = state_copy.get("buffer", 0)

    money_for_goals = calculate_money_for_goals(
        money_remaining,
        buffer_amount
    )

    # 4. Recalculate goal deadlines
    goals = state_copy["goals"]

    for goal in goals:

        if (
            goal.get("status") == "active"
            and goal.get("deadline") is not None
        ):
            goal["periods_left"] = calculate_weeks_left(
                goal["deadline"],
                reference_date
            )

    # 5. Recalculate goal requirements
    goals = update_goal_requirements(goals)

    # 6. Check feasibility
    plan_result = check_updated_plan(
        goals,
        money_for_goals
    )

    # 7. Allocate weekly goal savings
    allocation_result = allocate_goal_savings(
        goals,
        money_for_goals
    )

    return {
        "general_income": general_income,
        "restricted_income": restricted_income,
        "total_expenses": total_expenses,
        "money_remaining": money_remaining,
        "buffer": buffer_amount,
        "money_for_goals": money_for_goals,
        "goals": goals,
        "status": plan_result["status"],
        "total_required": plan_result["total_required"],
        "surplus": plan_result["surplus"],
        "shortfall": plan_result["shortfall"],
        "allocations": allocation_result["allocations"],
        "extra_money": allocation_result["extra_money"]
    }

In [ ]:
final_plan = replan_from_state(
    loaded_state,
    reference_date=date(2026, 10, 14)
)

print("Income:", final_plan["general_income"])
print("Expenses:", final_plan["total_expenses"])
print("Money remaining:", final_plan["money_remaining"])
print("Buffer:", final_plan["buffer"])
print("Money for goals:", final_plan["money_for_goals"])
print("Status:", final_plan["status"])
print("Required per week:", final_plan["total_required"])
print("Surplus:", final_plan["surplus"])
print("Shortfall:", final_plan["shortfall"])
print("Allocations:", final_plan["allocations"])

Income: 1350.0
Expenses: 828.8461538461538
Money remaining: 521.1538461538462
Buffer: 67.5
Money for goals: 453.6538461538462
Status: achievable
Required per week: 231.8421052631579
Surplus: 221.8117408906883
Shortfall: 0
Allocations: {'flight': 120.0, 'new PC': 86.84210526315789, 'bag': 25.0}